import { codigo, pista } from '../comun.js'

export default {
  id: "ferro-02-huecos",
  mundo: "ferrocarril",
  entorno: "vue3",
  tipo: "codigo",
  titulo: "Dejar un hueco para lo que no sabes",
  enunciado: codigo(
    "Un componente con props solo sirve para lo que previste. Un componente con **huecos**",
    "sirve para lo que se le ocurra a quien lo use, que es lo que lo hace reutilizable.",
    "",
    "Escribe el componente `Ficha` (guárdalo en una variable con ese nombre) con:",
    "",
    "- Un `<h3>` con la prop `titulo`.",
    "- Un `<div class=\"cuerpo\">` con un **hueco por defecto**, que ponga",
    "  `Sin datos` cuando no le metan nada.",
    "- Un `<footer>` con un **hueco llamado `pie`**, al que le pases el número de",
    "  la prop `casos`.",
    "",
    "Declara también `componente`, que use `Ficha` y le meta cosas por los dos huecos.",
  ),
  inicial: codigo(
    "const { ref } = Vue",
    "",
    "const Ficha = {",
    "  props: ['titulo', 'casos'],",
    "  template: `",
    "    <article>",
    "      <h3>...</h3>",
    "    </article>",
    "  `,",
    "}",
    "",
    "const componente = {",
    "  components: { Ficha },",
    "  template: `...`,",
    "}",
  ),
  solucion: codigo(
    "const { ref } = Vue",
    "",
    "const Ficha = {",
    "  props: ['titulo', 'casos'],",
    "  template: `",
    "    <article>",
    "      <h3>{{ titulo }}</h3>",
    "      <div class=\"cuerpo\"><slot>Sin datos</slot></div>",
    "      <footer><slot name=\"pie\" :casos=\"casos\" /></footer>",
    "    </article>",
    "  `,",
    "}",
    "",
    "const componente = {",
    "  components: { Ficha },",
    "  template: `",
    "    <Ficha titulo=\"Wax\" :casos=\"4\">",
    "      <p>Agente de Elendel</p>",
    "      <template #pie=\"{ casos }\">Lleva {{ casos }} casos</template>",
    "    </Ficha>",
    "  `,",
    "}",
  ),
  requisitos: [
    { tipo: "declaraVariable", valor: "Ficha" },
    { tipo: "declaraVariable", valor: "componente" },
    { tipo: "prohibeVar" },
  ],
  tests: [
    {
      nombre: "el título llega por prop",
      codigo: codigo(
        "const vista = montar(componente)",
        "esperar(vista.texto('h3')).diceLoMismoQue('Wax')",
      ),
    },
    {
      nombre: "lo que se mete por el hueco por defecto se pinta",
      codigo: codigo(
        "const vista = montar(componente)",
        "esperar(vista.texto('.cuerpo')).diceLoMismoQue('Agente de Elendel')",
      ),
    },
    {
      nombre: "el hueco con nombre recibe los casos y los enseña",
      codigo: codigo(
        "const vista = montar(componente)",
        "esperar(vista.texto('footer')).contiene('4')",
      ),
    },
    {
      nombre: "sin nada dentro, el hueco por defecto enseña su respaldo",
      codigo: codigo(
        "const vista = montar({ components: { Ficha }, template: '<Ficha titulo=\"X\" :casos=\"0\" />' })",
        "esperar(vista.texto('.cuerpo')).diceLoMismoQue('Sin datos')",
      ),
    },
  ],
  pistas: [
    pista("Un hueco se abre con `<slot />` en la plantilla del hijo. Lo que escribas **dentro** de esa etiqueta es lo que se enseña si nadie mete nada.", 0),
    pista("Para tener más de un hueco hay que ponerles nombre: `<slot name=\"pie\" />`, y quien lo use lo rellena con `<template #pie>`.", 1),
    pista("Para que el hueco reciba datos del hijo se le pasan como si fueran props: `<slot name=\"pie\" :casos=\"casos\" />`. Y quien lo rellena los recoge desestructurando: `<template #pie=\"{ casos }\">`.", 2),
  ],
  recompensa: { croquetas: 15 },
}
