import { codigo, pista } from '../comun.js'

export default {
  id: "ferro-02-huecos",
  mundo: "ferrocarril",
  entorno: "vue3",
  tipo: "codigo",
  titulo: "Dejar un hueco para lo que no sabes",
  enunciado: codigo(
    "Un componente con props solo sirve para lo que previste. Un componente con **huecos**",
    "sirve para lo que se le ocurra a quien lo use, que es lo que lo hace reutilizable.",
    "",
    "Escribe el componente `Ficha` (guárdalo en una variable con ese nombre) con:",
    "",
    "- Un `<h3>` con la prop `titulo`.",
    "- Un `<div class=\"cuerpo\">` con un **hueco por defecto**, que ponga",
    "  `Sin datos` cuando no le metan nada.",
    "- Un `<footer>` con un **hueco llamado `pie`**, al que le pases el número de",
    "  la prop `casos`.",
    "",
    "Declara también `componente`, que use `Ficha` y le meta cosas por los dos huecos.",
  ),
  inicial: codigo(
    "const { ref } = Vue",
    "",
    "const Ficha = {",
    "  props: ['titulo', 'casos'],",
    "  template: `",
    "    <article>",
    "      <h3>...</h3>",
    "    </article>",
    "  `,",
    "}",
    "",
    "const componente = {",
    "  components: { Ficha },",
    "  template: `...`,",
    "}",
  ),
  solucion: codigo(
    "const { ref } = Vue",
    "",
    "const Ficha = {",
    "  props: ['titulo', 'casos'],",
    "  template: `",
    "    <article>",
    "      <h3>{{ titulo }}</h3>",
    "      <div class=\"cuerpo\"><slot>Sin datos</slot></div>",
    "      <footer><slot name=\"pie\" :casos=\"casos\" /></footer>",
    "    </article>",
    "  `,",
    "}",
    "",
    "const componente = {",
    "  components: { Ficha },",
    "  template: `",
    "    <Ficha titulo=\"Wax\" :casos=\"4\">",
    "      <p>Agente de Elendel</p>",
    "      <template #pie=\"{ casos }\">Lleva {{ casos }} casos</template>",
    "    </Ficha>",
    "  `,",
    "}",
  ),
  requisitos: [
    { tipo: "declaraVariable", valor: "Ficha" },
    { tipo: "declaraVariable", valor: "componente" },
    { tipo: "prohibeVar" },
  ],
  tests: [
    {
      nombre: "el título llega por prop",
      codigo: codigo(
        "const vista = montar(componente)",
        "esperar(vista.texto('h3')).diceLoMismoQue('Wax')",
      ),
    },
    {
      nombre: "lo que se mete por el hueco por defecto se pinta",
      codigo: codigo(
        "const vista = montar(componente)",
        "esperar(vista.texto('.cuerpo')).diceLoMismoQue('Agente de Elendel')",
      ),
    },
    {
      nombre: "el hueco con nombre recibe los casos y los enseña",
      codigo: codigo(
        "const vista = montar(componente)",
        "esperar(vista.texto('footer')).contiene('4')",
      ),
    },
    {
      nombre: "sin nada dentro, el hueco por defecto enseña su respaldo",
      codigo: codigo(
        "const vista = montar({ components: { Ficha }, template: '<Ficha titulo=\"X\" :casos=\"0\" />' })",
        "esperar(vista.texto('.cuerpo')).diceLoMismoQue('Sin datos')",
      ),
    },
  ],
  // Un hueco se practica montando la ficha con otras cosas dentro. Las tandas
  // meten varios elementos por el hueco por defecto, dejan el pie sin rellenar y
  // pasan un cero, que es donde se ve si el hueco recibe datos de verdad.
  variantes: [
    {
      titulo: "Dejar un hueco para lo que no sabes · otra tanda",
      tests: [
        {
          nombre: "otra ficha, otro título y otros casos, y el pie los enseña",
          codigo: codigo(
            "const vista = montar({",
            "  components: { Ficha },",
            "  template: `",
            "    <Ficha titulo=\"Marasi\" :casos=\"9\">",
            "      <p>Ayudante del fiscal</p>",
            "      <template #pie=\"{ casos }\">Lleva {{ casos }} casos</template>",
            "    </Ficha>",
            "  `,",
            "})",
            "esperar(vista.texto('h3')).diceLoMismoQue('Marasi')",
            "esperar(vista.texto('footer')).contiene('9')",
          ),
        },
        {
          nombre: "por el hueco por defecto cabe más de una cosa",
          codigo: codigo(
            "const vista = montar({",
            "  components: { Ficha },",
            "  template: `",
            "    <Ficha titulo=\"Wayne\" :casos=\"1\">",
            "      <p>Sombrero</p>",
            "      <p>Chicle</p>",
            "    </Ficha>",
            "  `,",
            "})",
            "esperar(vista.contar('.cuerpo p')).igualA(2)",
          ),
        },
        {
          nombre: "sin rellenar el pie, el pie se queda vacío y no revienta",
          codigo: codigo(
            "const vista = montar({",
            "  components: { Ficha },",
            "  template: '<Ficha titulo=\"X\" :casos=\"3\" />',",
            "})",
            "esperar(vista.texto('footer')).igualA('')",
          ),
        },
        {
          nombre: "y el título es una prop de texto, no un hueco: va en el atributo",
          codigo: codigo(
            "const vista = montar({",
            "  components: { Ficha },",
            "  template: '<Ficha titulo=\"Steris\" :casos=\"0\" />',",
            "})",
            "esperar(vista.texto('h3')).diceLoMismoQue('Steris')",
          ),
        },
      ],
    },
    {
      titulo: "Dejar un hueco para lo que no sabes · y otra",
      tests: [
        {
          nombre: "un cero también baja por el hueco: cero no es «no hay nada»",
          codigo: codigo(
            "const vista = montar({",
            "  components: { Ficha },",
            "  template: `",
            "    <Ficha titulo=\"Recién llegado\" :casos=\"0\">",
            "      <template #pie=\"{ casos }\">Lleva {{ casos }} casos</template>",
            "    </Ficha>",
            "  `,",
            "})",
            "esperar(vista.texto('footer')).contiene('0')",
          ),
        },
        {
          nombre: "el respaldo del hueco por defecto solo sale cuando nadie mete nada",
          codigo: codigo(
            "const vacia = montar({",
            "  components: { Ficha },",
            "  template: '<Ficha titulo=\"A\" :casos=\"1\" />',",
            "})",
            "esperar(vacia.texto('.cuerpo')).diceLoMismoQue('Sin datos')",
            "const llena = montar({",
            "  components: { Ficha },",
            "  template: '<Ficha titulo=\"B\" :casos=\"1\"><em>Algo</em></Ficha>',",
            "})",
            "esperar(llena.texto('.cuerpo')).diceLoMismoQue('Algo')",
          ),
        },
        {
          nombre: "la ficha declara las dos props que recibe",
          codigo: codigo(
            "esperar(Ficha.props, 'las props de la ficha').contiene('titulo')",
            "esperar(Ficha.props, 'las props de la ficha').contiene('casos')",
          ),
        },
        {
          nombre: "dos fichas montadas a la vez, cada una con lo suyo",
          codigo: codigo(
            "const vista = montar({",
            "  components: { Ficha },",
            "  template: `",
            "    <div>",
            "      <Ficha titulo=\"Wax\" :casos=\"4\"><p>Uno</p></Ficha>",
            "      <Ficha titulo=\"Wayne\" :casos=\"7\"><p>Otro</p></Ficha>",
            "    </div>",
            "  `,",
            "})",
            "esperar(vista.textos('h3')).igualA(['Wax', 'Wayne'])",
            "esperar(vista.textos('.cuerpo')).igualA(['Uno', 'Otro'])",
          ),
        },
        {
          nombre: "y el cuerpo lleva su clase, que es por donde lo buscan los tests",
          codigo: codigo(
            "const vista = montar(componente)",
            "esperar(vista.existe('.cuerpo'), 'el cuerpo de la ficha').esVerdadero()",
          ),
        },
      ],
    },
  ],
  pistas: [
    pista("Un hueco se abre con `<slot />` en la plantilla del hijo. Lo que escribas **dentro** de esa etiqueta es lo que se enseña si nadie mete nada.", 0),
    pista("Para tener más de un hueco hay que ponerles nombre: `<slot name=\"pie\" />`, y quien lo use lo rellena con `<template #pie>`.", 1),
    pista("Para que el hueco reciba datos del hijo se le pasan como si fueran props: `<slot name=\"pie\" :casos=\"casos\" />`. Y quien lo rellena los recoge desestructurando: `<template #pie=\"{ casos }\">`.", 2),
  ],
  recompensa: { croquetas: 15 },
}
