import { codigo, pista } from '../comun.js'

export default {
  id: "ferro-06-rutas",
  mundo: "ferrocarril",
  entorno: "vue3",
  tipo: "etiquetar",
  titulo: "El mapa de la línea",
  enunciado: codigo(
    "Una aplicación de verdad tiene varias pantallas y una dirección para cada una. De eso",
    "se encarga **vue-router**, que este juego usa: cada `#/reto/...` de la barra de",
    "direcciones es una ruta suya.",
    "",
    "Aquí no se puede ejecutar —el router no está cargado en este sandbox—, así que toca",
    "reconocer las piezas. Elige un nombre y pulsa el trozo al que corresponde.",
  ),
  fragmentos: [
    { texto: "const rutas = [\n  { path: '/', component: Portada },\n  { path: " },
    { texto: "'/reto/:retoId'", etiqueta: "ruta con parámetro" },
    { texto: ", component: Reto, " },
    { texto: "props: true", etiqueta: "el parámetro llega como prop" },
    { texto: " },\n]\n\nconst router = " },
    { texto: "createRouter({ history: createWebHashHistory(), routes: rutas })", etiqueta: "creación del router" },
    { texto: "\n\nrouter." },
    { texto: "beforeEach((hacia, desde) => (hayPartida ? true : '/'))", etiqueta: "guarda de navegación" },
    { texto: "\n\n// En la plantilla:\n// " },
    { texto: "<RouterLink to=\"/colonia\">La colonia</RouterLink>", etiqueta: "enlace a otra ruta" },
    { texto: "\n// " },
    { texto: "<RouterView />", etiqueta: "dónde se pinta la pantalla actual" },
  ],
  etiquetas: [
    "ruta con parámetro",
    "el parámetro llega como prop",
    "creación del router",
    "guarda de navegación",
    "enlace a otra ruta",
    "dónde se pinta la pantalla actual",
    "componente hijo",
    "hueco con nombre",
    "estado compartido",
  ],
  porque: codigo(
    "Tres cosas que conviene llevarse:",
    "",
    "**Los dos puntos marcan un parámetro.** `'/reto/:retoId'` encaja con `/reto/es6-01` y",
    "con cualquier otro, y el trozo variable queda disponible como `retoId`.",
    "",
    "**`props: true` es la diferencia entre un componente atado al router y uno normal.**",
    "Con eso, el parámetro le llega como una prop cualquiera y el componente se puede",
    "probar sin router. Sin eso, tiene que ir a buscarlo a `useRoute()`, y entonces solo",
    "funciona dentro de una aplicación con rutas.",
    "",
    "**Una guarda decide si se puede entrar.** Devolver `true` deja pasar; devolver otra",
    "ruta redirige. Es donde se comprueba si hay sesión, o —como en este juego— si el",
    "mundo está desbloqueado.",
    "",
    "Y `<RouterView />` no es decoración: es **el hueco donde se pinta la pantalla que",
    "toque**. Sin él no se ve nada, aunque las rutas estén bien puestas.",
  ),
  pistas: [
    pista("Empieza por la plantilla, abajo: hay una etiqueta para ir a otro sitio y otra que marca dónde aparece lo que se va viendo.", 0),
    pista("En la lista de rutas hay dos trozos. Uno es la dirección, con algo dentro que no es fijo; el otro es una opción de una sola palabra que cambia cómo le llega ese algo al componente.", 1),
    pista("`beforeEach` se ejecuta antes de cada navegación y puede impedirla. Y quedan tres etiquetas que no encajan en ningún sitio: son señuelos de otros retos de este mundo.", 2),
  ],
  recompensa: { croquetas: 13 },
}
