import { codigo } from '../comun.js'

export default {
  id: "ruina-12-ruina",
  mundo: "ruina",
  entorno: "php",
  tipo: "codigo",
  jefe: true,
  acto: 2,
  titulo: "Acto II: Ruina",
  enunciado: codigo(
    "El último. No hay pistas y no hay nada nuevo.",
    "",
    "El registro del acto anterior aguanta lo que se le da bien. Ahora hay que hacer que aguante",
    "lo que le echen: datos incompletos, datos mentirosos y datos que no debería aceptar. Y que",
    "cuando no pueda, lo diga.",
    "",
    "**El contrato.** `interface Registrable` con `nombre(): string`, `netos(): int` y",
    "`prioridad(): int`.",
    "",
    "**Dos clases**, con su fábrica cada una:",
    "",
    "- `Expedicion` — nombre y sacos. `netos()` son los sacos menos los perdidos -que pueden no",
    "  venir-, `prioridad()` es `1`.",
    "- `Urgente` — hereda; `prioridad()` es `0` y `nombre()` lleva `'!'`.",
    "- `Expedicion::deArray(array $datos): Registrable` — construye una de las dos según",
    "  `$datos['urgente']`, con `'sin nombre'` y `0` por lo que falte. Lanza una",
    "  `InvalidArgumentException` con la palabra `nombre` si el nombre viene vacío.",
    "",
    "**El registro.** `class Registro` con:",
    "",
    "- `anotar(Registrable $una): void` — lanza con la palabra `netos` si los netos son",
    "  negativos, y con la palabra `repetida` si ya hay anotada una con ese mismo nombre. No",
    "  anota nada cuando lanza.",
    "- `cuantas(): int`, `total(): int`, `porPrioridad(): array` — como antes.",
    "- `informe(): string` — una línea por anotada en el orden de `porPrioridad()`, con el",
    "  formato `nombre: netos`, y al final `TOTAL: n`. Todas las líneas acaban en `PHP_EOL`.",
    "- `deLista(array $filas): self` — estática: construye un registro con todo lo que se pueda",
    "  anotar y **se salta en silencio** lo que no. Ni una excepción sale de aquí.",
    "",
    "Lo guardado no se toca desde fuera, y solo esos seis métodos son públicos en `Registro`.",
  ),
  inicial: codigo(
    "<?php",
    "",
    "interface Registrable",
    "{",
    "    public function nombre(): string;",
    "    public function netos(): int;",
    "    public function prioridad(): int;",
    "}",
    "",
    "// Las dos clases con su fábrica, y el registro con sus seis métodos.",
    "//",
    "// `deLista` es la única que no se queja de nada: recibe lo que llegue del",
    "// mundo, anota lo que puede y calla lo demás. Esa es la frontera.",
  ),
  solucion: codigo(
    "<?php",
    "",
    "interface Registrable",
    "{",
    "    public function nombre(): string;",
    "    public function netos(): int;",
    "    public function prioridad(): int;",
    "}",
    "",
    "class Expedicion implements Registrable",
    "{",
    "    public function __construct(",
    "        protected string $nombre,",
    "        protected int $sacos,",
    "        protected int $perdidos = 0,",
    "    ) {}",
    "",
    "    public static function deArray(array $datos): Registrable",
    "    {",
    "        $nombre = $datos['nombre'] ?? 'sin nombre';",
    "        if ($nombre === '') {",
    "            throw new InvalidArgumentException('el nombre no puede estar vacío');",
    "        }",
    "",
    "        $sacos = $datos['sacos'] ?? 0;",
    "        $perdidos = $datos['perdidos'] ?? 0;",
    "",
    "        return ($datos['urgente'] ?? false)",
    "            ? new Urgente($nombre, $sacos, $perdidos)",
    "            : new self($nombre, $sacos, $perdidos);",
    "    }",
    "",
    "    public function nombre(): string",
    "    {",
    "        return $this->nombre;",
    "    }",
    "",
    "    public function netos(): int",
    "    {",
    "        return $this->sacos - $this->perdidos;",
    "    }",
    "",
    "    public function prioridad(): int",
    "    {",
    "        return 1;",
    "    }",
    "}",
    "",
    "class Urgente extends Expedicion",
    "{",
    "    public function nombre(): string",
    "    {",
    "        return parent::nombre() . '!';",
    "    }",
    "",
    "    public function prioridad(): int",
    "    {",
    "        return 0;",
    "    }",
    "}",
    "",
    "class Registro",
    "{",
    "    private array $anotadas = [];",
    "",
    "    public static function deLista(array $filas): self",
    "    {",
    "        $registro = new self();",
    "        foreach ($filas as $fila) {",
    "            if (!is_array($fila)) {",
    "                continue;",
    "            }",
    "            try {",
    "                $registro->anotar(Expedicion::deArray($fila));",
    "            } catch (Throwable $error) {",
    "                continue;",
    "            }",
    "        }",
    "        return $registro;",
    "    }",
    "",
    "    public function anotar(Registrable $una): void",
    "    {",
    "        if ($una->netos() < 0) {",
    "            throw new InvalidArgumentException('los netos no pueden ser negativos');",
    "        }",
    "        if (in_array($una->nombre(), $this->nombres(), true)) {",
    "            throw new InvalidArgumentException('esa expedición está repetida');",
    "        }",
    "        $this->anotadas[] = $una;",
    "    }",
    "",
    "    public function cuantas(): int",
    "    {",
    "        return count($this->anotadas);",
    "    }",
    "",
    "    public function total(): int",
    "    {",
    "        return array_reduce($this->anotadas, fn($llevado, $una) => $llevado + $una->netos(), 0);",
    "    }",
    "",
    "    public function porPrioridad(): array",
    "    {",
    "        return array_map(fn($una) => $una->nombre(), $this->ordenadas());",
    "    }",
    "",
    "    public function informe(): string",
    "    {",
    "        $texto = array_reduce(",
    "            $this->ordenadas(),",
    "            fn($llevado, $una) => $llevado . $una->nombre() . ': ' . $una->netos() . PHP_EOL,",
    "            ''",
    "        );",
    "        return $texto . 'TOTAL: ' . $this->total() . PHP_EOL;",
    "    }",
    "",
    "    private function ordenadas(): array",
    "    {",
    "        $puestas = $this->anotadas;",
    "        usort(",
    "            $puestas,",
    "            fn($a, $b) => $a->prioridad() - $b->prioridad() ?: $b->netos() - $a->netos()",
    "        );",
    "        return $puestas;",
    "    }",
    "",
    "    private function nombres(): array",
    "    {",
    "        return array_map(fn($una) => $una->nombre(), $this->anotadas);",
    "    }",
    "}",
  ),
  requisitos: [
    { tipo: "usaPalabra", valor: "implements", texto: "El contrato se cumple con `implements`" },
    { tipo: "usaPalabra", valor: "extends", texto: "La urgente hereda" },
    { tipo: "usaPalabra", valor: "parent", texto: "Y reutiliza lo de su madre" },
    { tipo: "usaPalabra", valor: "static", texto: "Las dos fábricas son estáticas" },
    { tipo: "usaPalabra", valor: "throw", texto: "Lo que no se puede hacer se dice" },
    { tipo: "usaPalabra", valor: "catch", texto: "Y en la frontera se recoge" },
    { tipo: "usaPalabra", valor: "private", texto: "Lo guardado, cerrado" },
    { tipo: "alMenos", valor: "??", veces: 3, texto: "Lo que puede faltar se lee con `??`" },
  ],
  tests: [
    {
      nombre: "las dos clases dicen lo suyo",
      codigo: codigo(
        "$normal = new Expedicion('Fadrex', 12, 2);",
        "esperar([$normal->nombre(), $normal->netos(), $normal->prioridad()], 'la normal')",
        "  ->igualA(['Fadrex', 10, 1]);",
        "$urge = new Urgente('Urteau', 5);",
        "esperar([$urge->nombre(), $urge->netos(), $urge->prioridad()], 'la urgente')",
        "  ->igualA(['Urteau!', 5, 0]);",
      ),
    },
    {
      nombre: "la fábrica elige la clase según los datos",
      codigo: codigo(
        "esperar(Expedicion::deArray(['nombre' => 'A', 'sacos' => 1]) instanceof Urgente, 'la normal')->esFalso();",
        "esperar(Expedicion::deArray(['nombre' => 'A', 'sacos' => 1, 'urgente' => true]) instanceof Urgente, 'la urgente')->esVerdadero();",
      ),
    },
    {
      nombre: "y rellena lo que falta",
      codigo: codigo(
        "$una = Expedicion::deArray([]);",
        "esperar($una->nombre(), 'el nombre')->igualA('sin nombre');",
        "esperar($una->netos(), 'los netos')->igualA(0);",
      ),
    },
    {
      nombre: "un nombre vacío se rechaza, y eso no es lo mismo que no venir",
      codigo: codigo(
        "esperar(fn() => Expedicion::deArray(['nombre' => '']), 'la fábrica')->lanzaErrorQueDice('nombre');",
        "esperar(Expedicion::deArray([])->nombre(), 'sin la clave')->igualA('sin nombre');",
      ),
    },
    {
      nombre: "el registro suma y cuenta",
      codigo: codigo(
        "$registro = new Registro();",
        "$registro->anotar(new Expedicion('A', 10));",
        "$registro->anotar(new Urgente('B', 5));",
        "esperar($registro->cuantas(), 'cuántas')->igualA(2);",
        "esperar($registro->total(), 'el total')->igualA(15);",
      ),
    },
    {
      nombre: "ordena por prioridad y luego por netos",
      codigo: codigo(
        "$registro = new Registro();",
        "$registro->anotar(new Expedicion('normal-mucha', 9));",
        "$registro->anotar(new Urgente('urge-poca', 1));",
        "$registro->anotar(new Urgente('urge-mucha', 8));",
        "$registro->anotar(new Expedicion('normal-poca', 2));",
        "esperar($registro->porPrioridad(), 'el orden')->igualA(",
        "  ['urge-mucha!', 'urge-poca!', 'normal-mucha', 'normal-poca']",
        ");",
      ),
    },
    {
      nombre: "el informe sale con su formato y su total",
      codigo: codigo(
        "$registro = new Registro();",
        "$registro->anotar(new Expedicion('Fadrex', 10));",
        "$registro->anotar(new Urgente('Urteau', 4));",
        "esperar($registro->informe(), 'el informe')->igualA(",
        "  'Urteau!: 4' . PHP_EOL . 'Fadrex: 10' . PHP_EOL . 'TOTAL: 14' . PHP_EOL",
        ");",
      ),
    },
    {
      nombre: "el informe de un registro vacío es solo el total",
      codigo: "esperar((new Registro())->informe(), 'el informe')->igualA('TOTAL: 0' . PHP_EOL);",
    },
    {
      nombre: "los netos negativos se rechazan y no anotan",
      codigo: codigo(
        "$registro = new Registro();",
        "$registro->anotar(new Expedicion('buena', 5));",
        "esperar(fn() => $registro->anotar(new Expedicion('mala', 1, 9)), 'anotar')->lanzaErrorQueDice('netos');",
        "esperar($registro->cuantas(), 'cuántas')->igualA(1);",
      ),
    },
    {
      nombre: "una repetida se rechaza, y por nombre",
      codigo: codigo(
        "$registro = new Registro();",
        "$registro->anotar(new Expedicion('A', 5));",
        "esperar(fn() => $registro->anotar(new Expedicion('A', 9)), 'anotar la repetida')",
        "  ->lanzaErrorQueDice('repetida');",
        "esperar($registro->total(), 'el total')->igualA(5);",
      ),
    },
    {
      nombre: "y una urgente con el mismo nombre base NO está repetida: su nombre lleva el signo",
      codigo: codigo(
        "$registro = new Registro();",
        "$registro->anotar(new Expedicion('A', 5));",
        "$registro->anotar(new Urgente('A', 5));",
        "esperar($registro->cuantas(), 'cuántas')->igualA(2);",
        "esperar($registro->porPrioridad(), 'el orden')->igualA(['A!', 'A']);",
      ),
    },
    {
      nombre: "deLista anota lo que puede",
      codigo: codigo(
        "$registro = Registro::deLista([",
        "  ['nombre' => 'A', 'sacos' => 10],",
        "  ['nombre' => 'B', 'sacos' => 4, 'urgente' => true],",
        "]);",
        "esperar($registro->cuantas(), 'cuántas')->igualA(2);",
        "esperar($registro->total(), 'el total')->igualA(14);",
      ),
    },
    {
      nombre: "y se salta en silencio lo que no",
      codigo: codigo(
        "$registro = Registro::deLista([",
        "  ['nombre' => 'A', 'sacos' => 10],",
        "  'esto no es una fila',",
        "  ['nombre' => '', 'sacos' => 5],",
        "  ['nombre' => 'B', 'sacos' => 1, 'perdidos' => 9],",
        "  ['nombre' => 'A', 'sacos' => 3],",
        "  ['nombre' => 'C', 'sacos' => 2],",
        "]);",
        "esperar($registro->cuantas(), 'cuántas')->igualA(2);",
        "esperar($registro->porPrioridad(), 'el orden')->igualA(['A', 'C']);",
      ),
    },
    {
      nombre: "ni una excepción sale de deLista",
      codigo: codigo(
        "esperar(Registro::deLista(['roto', null, 5, ['nombre' => '']])->cuantas(), 'cuántas')->igualA(0);",
      ),
    },
    {
      nombre: "y deLista no imprime nada por el camino",
      codigo: codigo(
        "Registro::deLista(['roto', ['nombre' => 'A', 'sacos' => 1]]);",
        "esperar($consola, 'la consola')->igualA('');",
      ),
    },
    {
      nombre: "una lista vacía da un registro vacío",
      codigo: "esperar(Registro::deLista([])->informe(), 'el informe')->igualA('TOTAL: 0' . PHP_EOL);",
    },
    {
      nombre: "los ceros se anotan: cero no es negativo",
      codigo: codigo(
        "$registro = Registro::deLista([['nombre' => 'vacía', 'sacos' => 0]]);",
        "esperar($registro->cuantas(), 'cuántas')->igualA(1);",
        "esperar($registro->informe(), 'el informe')->contiene('vacía: 0');",
      ),
    },
    {
      nombre: "pedir el informe dos veces da lo mismo",
      codigo: codigo(
        "$registro = Registro::deLista([['nombre' => 'a', 'sacos' => 1], ['nombre' => 'b', 'sacos' => 9]]);",
        "esperar($registro->informe(), 'la primera vez')->igualA($registro->informe());",
      ),
    },
    {
      nombre: "lo guardado no se alcanza desde fuera",
      codigo: codigo(
        "$registro = Registro::deLista([['nombre' => 'a', 'sacos' => 1]]);",
        "esperar(array_keys(get_object_vars($registro)), 'las propiedades públicas')->igualA([]);",
      ),
    },
    {
      nombre: "y solo son públicos los seis métodos que se piden",
      codigo: codigo(
        "$publicos = array_map(",
        "    fn($m) => $m->getName(),",
        "    (new ReflectionClass('Registro'))->getMethods(ReflectionMethod::IS_PUBLIC)",
        ");",
        "sort($publicos);",
        "esperar($publicos, 'los métodos públicos')->igualA(",
        "  ['anotar', 'cuantas', 'deLista', 'informe', 'porPrioridad', 'total']",
        ");",
      ),
    },
    {
      nombre: "y el registro no deja entrar lo que no cumple el contrato",
      codigo: "esperar(fn() => (new Registro())->anotar('un texto'), 'anotar un texto')->lanzaError();",
    },
  ],
  recompensa: { croquetas: 25 },
}
