import { codigo, pista } from '../comun.js'

export default {
  id: "com-04-listas",
  mundo: "comisaria",
  entorno: "worker",
  tipo: "emparejar",
  titulo: "El tablón de buscados",
  enunciado: codigo(
    "Una lista guarda muchas cosas bajo un solo nombre. Es la estructura que más vas a",
    "usar, con diferencia.",
    "",
    "Empareja cada trozo de código con lo que vale, sobre esta lista:",
    "",
    "```js",
    "const buscados = ['Miles', 'Bleeder', 'Suit']",
    "```",
  ),
  apunte: codigo(
    "Un **array** —una lista— es una caja con muchos huecos numerados:",
    "",
    "```js",
    "const buscados = ['Miles', 'Bleeder', 'Suit']",
    "```",
    "",
    "## Se cuenta desde cero",
    "",
    "Esto no es un capricho, es una convención de toda la profesión, y hasta que se te",
    "hace natural la pisas cien veces:",
    "",
    "```js",
    "buscados[0]    // 'Miles'    el primero",
    "buscados[1]    // 'Bleeder'",
    "buscados[2]    // 'Suit'     el último",
    "buscados[3]    // undefined  ahí no hay nadie",
    "```",
    "",
    "Pedir una posición que no existe **no da error**: da `undefined`. Es JavaScript",
    "encogiéndose de hombros, y suele ser el origen del famoso «cannot read properties",
    "of undefined» tres líneas más abajo.",
    "",
    "## Cuántos hay",
    "",
    "```js",
    "buscados.length      // 3",
    "```",
    "",
    "Y de ahí sale la fórmula que se usa a diario: si hay 3 y se empieza en 0, el",
    "último está en la posición 2. O sea, `length - 1`:",
    "",
    "```js",
    "buscados[buscados.length - 1]    // 'Suit', sea cual sea el tamaño",
    "```",
    "",
    "## Meter y sacar",
    "",
    "```js",
    "buscados.push('Paalm')    // lo añade al final; ahora length es 4",
    "buscados.pop()            // saca el último y te lo devuelve",
    "buscados.includes('Suit') // true: ¿está ahí dentro?",
    "buscados.indexOf('Suit')  // 2: ¿en qué posición? -1 si no está",
    "```",
    "",
    "Ojo con `indexOf`: cuando no encuentra nada devuelve `-1`, no `undefined`. Y `-1`",
    "es un número verdadero, así que un `if (lista.indexOf(x))` se cumple justo cuando",
    "**no** está. Para preguntar si está, usa `includes` y te ahorras el disgusto.",
  ),
  parejas: [
    { izquierda: "buscados[0]", derecha: "'Miles'" },
    { izquierda: "buscados[2]", derecha: "'Suit'" },
    { izquierda: "buscados[3]", derecha: "undefined" },
    { izquierda: "buscados.length", derecha: "3" },
    { izquierda: "buscados[buscados.length - 1]", derecha: "el último, sea cual sea el tamaño" },
    { izquierda: "buscados.includes('Suit')", derecha: "true" },
    { izquierda: "buscados.indexOf('Nadie')", derecha: "-1" },
  ],
  pistas: [
    pista("Se cuenta desde cero: el primero es el 0, no el 1.", 0),
    pista("Hay tres nombres, así que `length` vale 3 y la última posición ocupada es la 2.", 1),
    pista("Pedir una posición vacía da `undefined`; buscar algo que no está con `indexOf` da `-1`.", 2),
  ],
  recompensa: { croquetas: 5 },
}
