import { codigo, pista } from '../comun.js'

export default {
  id: "com-07-objetos",
  mundo: "comisaria",
  entorno: "worker",
  tipo: "codigo",
  titulo: "La ficha de un sospechoso",
  enunciado: codigo(
    "Una lista guarda cosas **numeradas**. Un objeto las guarda **con nombre**, que es",
    "lo que hace falta cuando cada dato significa algo distinto.",
    "",
    "Escribe dos funciones:",
    "",
    "- `crearFicha(nombre, alias, recompensa)` — devuelve un objeto con esas tres",
    "  propiedades, más una cuarta, `capturado`, que empieza en `false`.",
    "- `describir(ficha)` — devuelve el texto ``'Miles, alias Dientes de Sangre: 500'``,",
    "  con los datos de la ficha que le pasen.",
  ),
  apunte: codigo(
    "Guardar a una persona en una lista sale mal enseguida:",
    "",
    "```js",
    "const sospechoso = ['Miles', 'Dientes de Sangre', 500]",
    "sospechoso[1]    // ...¿esto era el alias o la recompensa?",
    "```",
    "",
    "Con un objeto, cada dato lleva su etiqueta puesta:",
    "",
    "```js",
    "const sospechoso = {",
    "  nombre: 'Miles',",
    "  alias: 'Dientes de Sangre',",
    "  recompensa: 500,",
    "}",
    "",
    "sospechoso.alias    // 'Dientes de Sangre'",
    "```",
    "",
    "La regla rápida: si todos los elementos son **lo mismo** (muchos sospechosos), una",
    "lista. Si cada uno es **una cosa distinta** (el nombre, el alias, la recompensa),",
    "un objeto.",
    "",
    "## Leer y escribir",
    "",
    "```js",
    "sospechoso.recompensa            // 500",
    "sospechoso.recompensa = 800      // se cambia",
    "sospechoso.peligroso = true      // se añade una propiedad nueva, sin más",
    "sospechoso.altura                // undefined: no existe, y no da error",
    "```",
    "",
    "Con punto se accede cuando sabes el nombre al escribir el código. Con corchetes,",
    "cuando el nombre está en una variable:",
    "",
    "```js",
    "const campo = 'alias'",
    "sospechoso[campo]     // 'Dientes de Sangre'",
    "sospechoso.campo      // undefined: busca una propiedad llamada 'campo'",
    "```",
    "",
    "## Una función que fabrica objetos",
    "",
    "```js",
    "function crear(nombre, alias) {",
    "  return {",
    "    nombre: nombre,",
    "    alias: alias,",
    "    capturado: false,",
    "  }",
    "}",
    "```",
    "",
    "Y como escribir `nombre: nombre` cansa, hay una forma corta: si la propiedad se",
    "llama igual que la variable, se pone una vez.",
    "",
    "```js",
    "return { nombre, alias, capturado: false }",
    "```",
    "",
    "Es exactamente lo mismo, y así es como lo vas a ver escrito en todas partes.",
    "",
    "## Cuidado con las llaves y la flecha",
    "",
    "Una función flecha que devuelve un objeto necesita paréntesis alrededor:",
    "",
    "```js",
    "const crear = (nombre) => ({ nombre })     // devuelve el objeto",
    "const roto  = (nombre) => { nombre }       // devuelve undefined",
    "```",
    "",
    "Sin los paréntesis, JavaScript entiende que esas llaves son el cuerpo de la",
    "función, no un objeto. No da error: devuelve `undefined` y te deja buscándolo.",
  ),
  inicial: codigo(
    "function crearFicha(nombre, alias, recompensa) {",
    "  // Un objeto con cuatro propiedades.",
    "}",
    "",
    "function describir(ficha) {",
    "  // 'Miles, alias Dientes de Sangre: 500'",
    "}",
    "",
    "const miles = crearFicha('Miles', 'Dientes de Sangre', 500)",
    "console.log(describir(miles))",
  ),
  solucion: codigo(
    "function crearFicha(nombre, alias, recompensa) {",
    "  return { nombre, alias, recompensa, capturado: false }",
    "}",
    "",
    "function describir(ficha) {",
    "  return `${ficha.nombre}, alias ${ficha.alias}: ${ficha.recompensa}`",
    "}",
    "",
    "const miles = crearFicha('Miles', 'Dientes de Sangre', 500)",
    "console.log(describir(miles))",
  ),
  requisitos: [
    { tipo: "usaPlantilla" },
  ],
  tests: [
    {
      nombre: "la ficha guarda los tres datos",
      codigo: codigo(
        "const f = crearFicha('Miles', 'Dientes de Sangre', 500)",
        "esperar(f.nombre).igualA('Miles')",
        "esperar(f.alias).igualA('Dientes de Sangre')",
        "esperar(f.recompensa).igualA(500)",
      ),
    },
    {
      nombre: "y nace sin capturar",
      codigo: "esperar(crearFicha('Miles', 'x', 1).capturado).esFalso()",
    },
    {
      nombre: "describir arma el texto con los datos de la ficha",
      codigo: codigo(
        "const f = crearFicha('Miles', 'Dientes de Sangre', 500)",
        "esperar(describir(f)).igualA('Miles, alias Dientes de Sangre: 500')",
      ),
    },
    {
      nombre: "describir sirve para cualquier ficha, no solo para Miles",
      codigo: codigo(
        "const f = crearFicha('Paalm', 'Bleeder', 1200)",
        "esperar(describir(f)).igualA('Paalm, alias Bleeder: 1200')",
      ),
    },
  ],
  pistas: [
    pista("`crearFicha` tiene que **devolver** el objeto. Si empiezas la línea con `return {`, ya lo tienes casi.", 0),
    pista("En `describir` no puedes escribir 'Miles' a mano: el segundo test le pasa otra ficha distinta. Saca los datos de `ficha.nombre`, `ficha.alias` y `ficha.recompensa`.", 1),
    pista("`return { nombre, alias, recompensa, capturado: false }` y `` return `${ficha.nombre}, alias ${ficha.alias}: ${ficha.recompensa}` ``", 2),
  ],
  recompensa: { croquetas: 8 },
}
