import { codigo, pista } from '../comun.js'

export default {
  id: "com-09-texto",
  mundo: "comisaria",
  entorno: "worker",
  tipo: "bug",
  titulo: "El cartel que sale torcido",
  enunciado: codigo(
    "Este código imprime los carteles de busca y captura. Funciona... casi.",
    "",
    "Los nombres llegan del registro como vienen: con espacios de más y sin cuidar las",
    "mayúsculas. El cartel tiene que salir siempre igual: **nombre en mayúsculas, sin",
    "espacios sobrantes**, y con la recompensa.",
    "",
    "Arregla `hacerCartel` para que los cuatro tests pasen.",
  ),
  apunte: codigo(
    "Un texto también tiene sus métodos, y son de los que más se usan:",
    "",
    "```js",
    "const nombre = '  miles Dagouter  '",
    "",
    "nombre.trim()          // 'miles Dagouter'   quita espacios de los dos lados",
    "nombre.toUpperCase()   // '  MILES DAGOUTER  '",
    "nombre.toLowerCase()   // '  miles dagouter  '",
    "nombre.length          // 19, espacios incluidos",
    "nombre.includes('Dag') // true",
    "nombre.replace('miles', 'Miles')",
    "nombre.split(' ')      // lo parte por los espacios y devuelve una lista",
    "```",
    "",
    "## Lo que casi nadie ve la primera vez",
    "",
    "**Ninguno de estos cambia el texto original.** Todos devuelven uno nuevo:",
    "",
    "```js",
    "let nombre = '  miles  '",
    "nombre.trim()          // devuelve 'miles'...",
    "console.log(nombre)    // ...pero nombre sigue siendo '  miles  '",
    "",
    "nombre = nombre.trim() // así sí",
    "```",
    "",
    "En JavaScript los textos son **inmutables**: no se pueden modificar, solo se pueden",
    "fabricar otros. Llamar a `.trim()` y no recoger el resultado es tirar el trabajo a",
    "la basura, y es un fallo que se comete constantemente.",
    "",
    "## Se encadenan",
    "",
    "Como cada uno devuelve un texto nuevo, se pueden enganchar uno detrás de otro:",
    "",
    "```js",
    "nombre.trim().toUpperCase()   // 'MILES'",
    "```",
    "",
    "Se leen de izquierda a derecha: primero quita los espacios, y a lo que salga de",
    "ahí le pone las mayúsculas. El orden importa menos aquí, pero en general importa.",
  ),
  inicial: codigo(
    "function hacerCartel(nombre, recompensa) {",
    "  nombre.trim()",
    "  nombre.toUpperCase()",
    "  return `SE BUSCA: ${nombre} (${recompensa})`",
    "}",
    "",
    "console.log(hacerCartel('  miles Dagouter  ', 500))",
  ),
  solucion: codigo(
    "function hacerCartel(nombre, recompensa) {",
    "  const limpio = nombre.trim().toUpperCase()",
    "  return `SE BUSCA: ${limpio} (${recompensa})`",
    "}",
    "",
    "console.log(hacerCartel('  miles Dagouter  ', 500))",
  ),
  tests: [
    {
      nombre: "quita los espacios y pone mayúsculas",
      codigo: "esperar(hacerCartel('  miles Dagouter  ', 500)).igualA('SE BUSCA: MILES DAGOUTER (500)')",
    },
    {
      nombre: "también con un nombre que ya venía limpio",
      codigo: "esperar(hacerCartel('Paalm', 1200)).igualA('SE BUSCA: PAALM (1200)')",
    },
    {
      nombre: "los espacios de dentro no se tocan",
      codigo: "esperar(hacerCartel(' the suit ', 90)).igualA('SE BUSCA: THE SUIT (90)')",
    },
    {
      nombre: "no estropea el nombre que le pasaron",
      codigo: codigo(
        "const original = '  miles  '",
        "hacerCartel(original, 1)",
        "esperar(original).igualA('  miles  ')",
      ),
    },
  ],
  pistas: [
    pista("Las dos primeras líneas hacen el trabajo bien. El problema es lo que pasa con el resultado.", 0),
    pista("`nombre.trim()` no cambia `nombre`: devuelve un texto nuevo. Si nadie lo recoge, se pierde.", 1),
    pista("Los dos métodos están bien elegidos y bien encadenados. Lo que falta es que alguien recoja lo que devuelven: hace falta una variable nueva con ese resultado, y usarla en la plantilla en lugar de la que te llegó.", 2),
  ],
  recompensa: { croquetas: 7 },
}
