/**
 * El apunte de Wax para «elendel-02-json».
 *
 * Vive fuera del reto y se carga cuando se abre, no al arrancar el juego.
 * Los apuntes son lo más largo que hay aquí -y tienen que serlo, porque son
 * la lección- así que si viajaran en el paquete inicial cada lección nueva
 * haría más lento el arranque para todo el mundo.
 */
import { codigo } from '../retos/comun.js'

export default codigo(
  "Todo lo que llega de fuera llega como **texto**. Da igual que sea un servidor, un archivo o",
  "otro programa: por el cable solo pasan caracteres. Y casi siempre con la misma forma, JSON.",
  "",
  "## Dos funciones y ya está",
  "",
  "```js",
  "const objeto = JSON.parse(texto)        // texto  → datos",
  "const texto = JSON.stringify(objeto)    // datos  → texto",
  "```",
  "",
  "Eso es el noventa por ciento de lo que se usa. Lo interesante es lo que pasa cuando algo no",
  "sale bien.",
  "",
  "## `parse` no avisa: lanza",
  "",
  "```js",
  "JSON.parse('{ esto no es json')",
  "// SyntaxError: Expected property name or '}' in JSON at position 2 (line 1 column 3)",
  "```",
  "",
  "No devuelve `null`, no devuelve `undefined`: **rompe el programa**. Y como los datos de",
  "fuera vienen rotos mucho más a menudo de lo que nadie confiesa —un servidor que devuelve una",
  "página de error en vez de datos, una respuesta cortada a medias—, todo `JSON.parse` de",
  "datos que no controlas va dentro de un `try`:",
  "",
  "```js",
  "function leerParte(texto) {",
  "  try {",
  "    return JSON.parse(texto)",
  "  } catch {",
  "    return null",
  "  }",
  "}",
  "```",
  "",
  "Fíjate en el `catch` sin paréntesis: se puede omitir el error cuando no lo vas a mirar. Y",
  "fíjate también en que aquí sí está justificado no mirarlo, porque solo hay una razón posible",
  "para que falle.",
  "",
  "## Lo que JSON no sabe guardar",
  "",
  "JSON es más pobre que JavaScript, y la diferencia se paga:",
  "",
  "```js",
  "JSON.stringify({",
  "  cuando: new Date(),        // → texto ISO. Ya no es una fecha",
  "  buscar: () => {},          // → desaparece",
  "  vacio: undefined,          // → desaparece",
  "  nada: null,                // → null. Este sí sobrevive",
  "  muchos: new Set([1, 2]),   // → {}",
  "  enorme: 10n,               // → TypeError",
  "})",
  "```",
  "",
  "Las dos que más duelen:",
  "",
  "**Las fechas se van y no vuelven.** `JSON.stringify` convierte una `Date` en texto, y",
  "`JSON.parse` no la reconstruye: te devuelve el texto. Si guardas una fecha y la lees, tienes",
  "un texto, y `fecha.getFullYear()` revienta. Hay que reconstruirla a mano con `new Date(...)`.",
  "",
  "**Lo que vale `undefined` desaparece sin avisar.** No queda ni la clave. Un objeto con",
  "quince campos puede volver con doce y sin ningún error.",
  "",
  "## El truco de la copia profunda, y por qué no",
  "",
  "Verás esto por ahí:",
  "",
  "```js",
  "const copia = JSON.parse(JSON.stringify(original))",
  "```",
  "",
  "Funciona, y se lleva por delante todo lo de la lista anterior. Hoy hay una función que hace",
  "bien lo que ese truco hacía a medias: `structuredClone(original)`. Cuando veas el truco en",
  "código antiguo, ya sabes qué intentaba hacer.",
  "",
  "## Los dos argumentos de más",
  "",
  "`stringify` acepta un tercer argumento que sirve mucho para mirar cosas:",
  "",
  "```js",
  "JSON.stringify(parte, null, 2)     // con saltos de línea y dos espacios de sangría",
  "```",
  "",
  "Un objeto grande en una sola línea no hay quien lo lea; con ese `2` sale legible. Es lo",
  "primero que se hace al depurar algo que viene de fuera.",
  "",
  "Y el segundo argumento permite elegir o transformar campos, que es la forma limpia de no",
  "mandar a ningún sitio cosas que no deberían salir:",
  "",
  "```js",
  "JSON.stringify(usuario, ['nombre', 'ciudad'])    // solo esos dos",
  "```",
  "",
  "## Lo que despista",
  "",
  "**Las claves llevan comillas dobles. Siempre.** `{ nombre: 'Wax' }` es JavaScript válido y",
  "JSON inválido. En JSON tiene que ser `{\"nombre\": \"Wax\"}`, con dobles, y sin coma al final",
  "del último elemento. Esa coma sobrante es el error de JSON más repetido.",
  "",
  "**JSON no admite comentarios.** Por eso los archivos de configuración en JSON son",
  "incómodos, y por eso existen formatos alternativos.",
  "",
  "**`JSON.parse('null')` devuelve `null` y no es un error.** Así que comprobar `if (!datos)`",
  "después de un parse puede confundir «vino un null» con «falló».",
  "",
  "**Un texto que empieza por `<` casi siempre es HTML.** El error lo dice tal cual:",
  "",
  "```",
  "SyntaxError: Unexpected token '<', \"<!DOCTYPE html>\" is not valid JSON",
  "```",
  "",
  "Eso no significa que el JSON esté mal formado: significa que el servidor te ha mandado una",
  "página de error en vez de datos. Es el diagnóstico más rentable de esta lección, porque la",
  "primera reacción de todo el mundo es ponerse a revisar el `parse`.",
  "",
  "Y la coma sobrante, que es el otro clásico, también se nombra sola:",
  "",
  "```",
  "JSON.parse('{\"a\":1,}')",
  "// SyntaxError: Expected double-quoted property name in JSON at position 7",
  "```",
  "",
  "## Pruébalo tú",
  "",
  "¿Qué sale?",
  "",
  "```js",
  "const original = {",
  "  ciudad: 'Elendel',",
  "  fundada: new Date('2015-03-14T00:00:00Z'),",
  "  buscar: () => 'nada',",
  "  alias: undefined,",
  "  agentes: ['Wax', 'Wayne'],",
  "}",
  "",
  "const texto = JSON.stringify(original)",
  "const vuelta = JSON.parse(texto)",
  "",
  "console.log(Object.keys(vuelta))",
  "console.log(typeof vuelta.fundada)",
  "```",
  "",
  "Sale `['ciudad', 'fundada', 'agentes']` y después `string`.",
  "",
  "Se han perdido dos campos por el camino, sin un solo error, y la fecha ha vuelto convertida",
  "en texto. Si el programa siguiera y llamara a `vuelta.fundada.getUTCFullYear()`, ahí sí",
  "reventaría — cuatro pasos después del sitio donde se rompió de verdad.",
  "",
  "## Cómo se plantea",
  "",
  "Con datos que vienen de fuera, siempre igual:",
  "",
  "1. **Envuelve el `parse` en un `try`.** Sin excepción, si no controlas el origen.",
  "2. **Comprueba la forma, no solo que se pudo leer.** Que sea JSON válido no significa que",
  "   traiga los campos que esperas. `parte.agentes.length` revienta igual si `agentes` no vino.",
  "3. **Reconstruye las fechas** a mano, y apúntate cuáles son.",
  "4. **Al depurar, `JSON.stringify(x, null, 2)`.** Ver el dato de verdad ahorra más tiempo que",
  "   cualquier suposición.",
)
