import { codigo, pista } from '../comun.js'

export default {
  id: "taller-01-clases",
  mundo: "taller",
  entorno: "worker",
  tipo: "codigo",
  titulo: "Objetos que saben hacer cosas",
  enunciado: codigo(
    "Hasta ahora tus objetos eran **datos**. Una clase es un molde que fabrica objetos",
    "con datos **y** con comportamiento pegado.",
    "",
    "Escribe la clase `Revolver`:",
    "",
    "- El constructor recibe la capacidad del tambor y lo deja **cargado del todo**.",
    "- `disparar()` — gasta una bala y devuelve `true`. Si no quedaba ninguna, no gasta",
    "  nada y devuelve `false`.",
    "- `recargar()` — vuelve a dejarlo lleno.",
    "- `get vacio` — vale `true` cuando no quedan balas.",
    "",
    "Las balas que queden se guardan en la propiedad `balas`.",
  ),
  inicial: codigo(
    "class Revolver {",
    "  constructor(capacidad) {",
    "    // guarda la capacidad y déjalo cargado",
    "  }",
    "",
    "  // disparar(), recargar() y el get vacio",
    "}",
    "",
    "const arma = new Revolver(6)",
    "arma.disparar()",
    "console.log(arma.balas)",
  ),
  solucion: codigo(
    "class Revolver {",
    "  constructor(capacidad) {",
    "    this.capacidad = capacidad",
    "    this.balas = capacidad",
    "  }",
    "",
    "  disparar() {",
    "    if (this.balas === 0) return false",
    "    this.balas -= 1",
    "    return true",
    "  }",
    "",
    "  recargar() {",
    "    this.balas = this.capacidad",
    "  }",
    "",
    "  get vacio() {",
    "    return this.balas === 0",
    "  }",
    "}",
    "",
    "const arma = new Revolver(6)",
    "arma.disparar()",
    "console.log(arma.balas)",
  ),
  requisitos: [
    { tipo: "usaDeclaracion", valor: "class" },
  ],
  tests: [
    {
      nombre: "nace cargado del todo",
      codigo: "esperar(new Revolver(6).balas).igualA(6)",
    },
    {
      nombre: "la capacidad la decide quien lo fabrica",
      codigo: "esperar(new Revolver(2).balas).igualA(2)",
    },
    {
      nombre: "disparar gasta una bala y dice que sí",
      codigo: codigo(
        "const a = new Revolver(6)",
        "esperar(a.disparar()).esVerdadero()",
        "esperar(a.balas).igualA(5)",
      ),
    },
    {
      nombre: "con el tambor vacío no dispara ni se pone en negativo",
      codigo: codigo(
        "const a = new Revolver(1)",
        "a.disparar()",
        "esperar(a.disparar()).esFalso()",
        "esperar(a.balas).igualA(0)",
      ),
    },
    {
      nombre: "recargar lo deja como estaba",
      codigo: codigo(
        "const a = new Revolver(6)",
        "a.disparar()",
        "a.disparar()",
        "a.recargar()",
        "esperar(a.balas).igualA(6)",
      ),
    },
    {
      nombre: "vacio se pide sin paréntesis y siempre está al día",
      codigo: codigo(
        "const a = new Revolver(1)",
        "esperar(a.vacio).esFalso()",
        "a.disparar()",
        "esperar(a.vacio).esVerdadero()",
      ),
    },
    {
      nombre: "dos revólveres no comparten balas",
      codigo: codigo(
        "const a = new Revolver(6)",
        "const b = new Revolver(6)",
        "a.disparar()",
        "esperar(b.balas).igualA(6)",
      ),
    },
  ],
  pistas: [
    pista("Dentro de la clase, todo lo que quieras recordar entre llamadas se guarda en `this.algo`.", 0),
    pista("`recargar` necesita saber a cuánto volver, así que la capacidad hay que guardarla en el constructor, no solo usarla.", 1),
    pista("Sal pronto del caso raro: la primera línea de `disparar` comprueba si el tambor está a cero y se va con `false` sin tocar nada. Todo lo que venga detrás ya puede dar por hecho que queda al menos una bala, y así el método se lee de un vistazo.", 2),
  ],
  recompensa: { croquetas: 10 },
}
