import { codigo, pista } from '../comun.js'

export default {
  id: "taller-03-errores",
  mundo: "taller",
  entorno: "worker",
  tipo: "codigo",
  titulo: "Cuando algo va mal a propósito",
  enunciado: codigo(
    "Hasta ahora, cuando algo iba mal, el programa reventaba. Un programa serio decide",
    "**qué falla, cómo se avisa y quién lo recoge**.",
    "",
    "Escribe dos cosas:",
    "",
    "- `retirar(saldo, cantidad)` — devuelve el saldo que queda. Si la cantidad no es",
    "  positiva, **lanza** un error con el mensaje `'La cantidad tiene que ser positiva'`.",
    "  Si no hay saldo suficiente, lanza `'Saldo insuficiente'`.",
    "- `retirarSinRiesgo(saldo, cantidad)` — llama a la anterior y **recoge** el error:",
    "  devuelve `{ ok: true, saldo }` si sale bien, y `{ ok: false, error }` con el",
    "  mensaje si no.",
  ),
  apunte: codigo(
    "Devolver `null` cuando algo va mal parece cómodo y sale caro:",
    "",
    "```js",
    "const restante = retirar(100, 500)   // null",
    "// ...cincuenta líneas después",
    "console.log(restante + 10)           // 10. ¿Y esto de dónde sale?",
    "```",
    "",
    "El problema no es el `null`: es que **el fallo viaja en silencio** y revienta lejos",
    "de donde se produjo. Un error, en cambio, para el programa en el sitio exacto:",
    "",
    "```js",
    "if (cantidad <= 0) {",
    "  throw new Error('La cantidad tiene que ser positiva')",
    "}",
    "```",
    "",
    "`throw` corta la función ahí mismo, como un `return` pero de mala manera: nada de",
    "lo que venga después se ejecuta, y el error sube llamada a llamada hasta que",
    "alguien lo recoja o hasta que se acabe el programa.",
    "",
    "## Recogerlo",
    "",
    "```js",
    "try {",
    "  const restante = retirar(saldo, cantidad)",
    "  return { ok: true, saldo: restante }",
    "} catch (error) {",
    "  return { ok: false, error: error.message }",
    "}",
    "```",
    "",
    "En `try` va lo que puede salir mal. Si algo lanza, se salta el resto del `try` y",
    "entra en `catch` con el error entre las manos. `error.message` es el texto que le",
    "pusiste al `new Error(...)`.",
    "",
    "## Dónde poner cada cosa",
    "",
    "Esta es la parte que no es sintaxis y sí es criterio:",
    "",
    "- **Lanza** en la función que **detecta** el problema. Ella sabe qué ha pasado.",
    "- **Recoge** donde se puede **hacer algo** al respecto: enseñar un aviso,",
    "  reintentar, apuntarlo en el registro.",
    "",
    "Un `try/catch` alrededor de todo, con un `catch` vacío, es peor que no ponerlo:",
    "convierte un fallo ruidoso en un fallo silencioso, y los silenciosos son los que",
    "te tienen tres días buscando.",
  ),
  inicial: codigo(
    "function retirar(saldo, cantidad) {",
    "  // lanza si la cantidad no vale o si no llega el saldo",
    "}",
    "",
    "function retirarSinRiesgo(saldo, cantidad) {",
    "  // llama a retirar y recoge lo que pase",
    "}",
    "",
    "console.log(retirarSinRiesgo(100, 30))",
    "console.log(retirarSinRiesgo(100, 500))",
  ),
  solucion: codigo(
    "function retirar(saldo, cantidad) {",
    "  if (cantidad <= 0) {",
    "    throw new Error('La cantidad tiene que ser positiva')",
    "  }",
    "  if (cantidad > saldo) {",
    "    throw new Error('Saldo insuficiente')",
    "  }",
    "  return saldo - cantidad",
    "}",
    "",
    "function retirarSinRiesgo(saldo, cantidad) {",
    "  try {",
    "    return { ok: true, saldo: retirar(saldo, cantidad) }",
    "  } catch (error) {",
    "    return { ok: false, error: error.message }",
    "  }",
    "}",
    "",
    "console.log(retirarSinRiesgo(100, 30))",
    "console.log(retirarSinRiesgo(100, 500))",
  ),
  requisitos: [
    { tipo: "usaLlamada", valor: "Error" },
  ],
  tests: [
    {
      nombre: "una retirada normal descuenta del saldo",
      codigo: "esperar(retirar(100, 30)).igualA(70)",
    },
    {
      nombre: "retirar lo justo deja el saldo a cero",
      codigo: "esperar(retirar(100, 100)).igualA(0)",
    },
    {
      nombre: "una cantidad negativa lanza, no devuelve",
      codigo: "esperar(() => retirar(100, -5)).lanzaError('La cantidad tiene que ser positiva')",
    },
    {
      nombre: "el cero tampoco es una cantidad válida",
      codigo: "esperar(() => retirar(100, 0)).lanzaError('La cantidad tiene que ser positiva')",
    },
    {
      nombre: "sin saldo suficiente lanza el otro error",
      codigo: "esperar(() => retirar(100, 500)).lanzaError('Saldo insuficiente')",
    },
    {
      nombre: "la versión sin riesgo devuelve el saldo cuando todo va bien",
      codigo: codigo(
        "const r = retirarSinRiesgo(100, 30)",
        "esperar(r.ok).esVerdadero()",
        "esperar(r.saldo).igualA(70)",
      ),
    },
    {
      nombre: "y recoge el error en vez de reventar",
      codigo: codigo(
        "const r = retirarSinRiesgo(100, 500)",
        "esperar(r.ok).esFalso()",
        "esperar(r.error).igualA('Saldo insuficiente')",
      ),
    },
    {
      nombre: "recoge también el de la cantidad",
      codigo: "esperar(retirarSinRiesgo(100, -1).error).igualA('La cantidad tiene que ser positiva')",
    },
  ],
  pistas: [
    pista("Las dos comprobaciones van al principio de `retirar`, antes de hacer ninguna cuenta. Es el patrón de «salir pronto».", 0),
    pista("`throw new Error('...')` no se devuelve con `return`: se lanza, y ya corta la función él solo.", 1),
    pista("En `retirarSinRiesgo` el `return` con el resultado va **dentro** del `try`. Si lo pones fuera, se ejecutará también cuando haya habido error.", 2),
  ],
  recompensa: { croquetas: 10 },
}
