import { codigo, pista } from '../comun.js'

export default {
  id: "taller-04-copias",
  mundo: "taller",
  entorno: "worker",
  tipo: "bug",
  titulo: "La copia que no era una copia",
  enunciado: codigo(
    "Este código guarda una plantilla de equipo y prepara una salida a partir de ella.",
    "Se supone que la plantilla no se toca nunca.",
    "",
    "Ejecútalo. Verás que la plantilla acaba con gente que nadie metió ahí.",
    "",
    "Arregla `prepararSalida` para que la plantilla original quede intacta.",
  ),
  apunte: codigo(
    "Este es **el** fallo que más horas cuesta de toda la lista, y no es difícil: es",
    "invisible.",
    "",
    "```js",
    "let a = 5",
    "let b = a",
    "b = 9",
    "console.log(a)      // 5. Todo normal.",
    "",
    "const lista = ['Wax']",
    "const otra = lista",
    "otra.push('Wayne')",
    "console.log(lista)  // ['Wax', 'Wayne'] ¿¿cómo??",
    "```",
    "",
    "Los números, los textos y los booleanos se copian **enteros**. Las listas y los",
    "objetos, no: lo que se copia es **la dirección**. `otra` y `lista` no son dos",
    "listas parecidas; son dos nombres del mismo sitio.",
    "",
    "Y `const` no protege de esto: `const` impide que le des otra lista a ese nombre,",
    "no impide que le metan cosas a la que ya hay.",
    "",
    "## Copiar de verdad",
    "",
    "```js",
    "const copia = [...lista]              // lista nueva con lo mismo dentro",
    "const copia = { ...objeto }           // objeto nuevo con lo mismo dentro",
    "```",
    "",
    "Los tres puntos van desparramando el contenido dentro de unos corchetes o unas",
    "llaves nuevas. A partir de ahí son cosas distintas y tocar una no toca la otra.",
    "",
    "Y sin copiar nada, muchos métodos ya devuelven una lista nueva en vez de tocar la",
    "tuya: `map`, `filter`, `slice`, `concat`. Los que sí modifican la original son",
    "`push`, `pop`, `splice`, `sort` y `reverse`. Merece la pena saberse esa segunda",
    "lista, que es más corta.",
    "",
    "## La copia es de un solo piso",
    "",
    "```js",
    "const original = { nombre: 'Wax', armas: ['Vindicación'] }",
    "const copia = { ...original }",
    "copia.armas.push('escopeta')",
    "console.log(original.armas)    // ['Vindicación', 'escopeta'] otra vez",
    "```",
    "",
    "El `...` copia el primer nivel. La lista de dentro sigue siendo **la misma lista**,",
    "porque lo que se copió fue su dirección. Con datos anidados hay que copiar también",
    "lo de dentro, a mano o con `structuredClone(original)`.",
  ),
  inicial: codigo(
    "const PLANTILLA = ['Wax', 'Wayne']",
    "",
    "function prepararSalida(refuerzo) {",
    "  const equipo = PLANTILLA",
    "  equipo.push(refuerzo)",
    "  return equipo",
    "}",
    "",
    "console.log(prepararSalida('Marasi'))",
    "console.log(PLANTILLA)",
  ),
  solucion: codigo(
    "const PLANTILLA = ['Wax', 'Wayne']",
    "",
    "function prepararSalida(refuerzo) {",
    "  const equipo = [...PLANTILLA]",
    "  equipo.push(refuerzo)",
    "  return equipo",
    "}",
    "",
    "console.log(prepararSalida('Marasi'))",
    "console.log(PLANTILLA)",
  ),
  requisitos: [
    { tipo: "usaSpread" },
  ],
  tests: [
    {
      nombre: "la salida lleva a los tres",
      codigo: "esperar(prepararSalida('Marasi')).igualA(['Wax', 'Wayne', 'Marasi'])",
    },
    {
      nombre: "y la plantilla se queda como estaba",
      codigo: codigo(
        "prepararSalida('Marasi')",
        "esperar(PLANTILLA).igualA(['Wax', 'Wayne'])",
      ),
    },
    {
      nombre: "dos salidas seguidas no se contaminan entre ellas",
      codigo: codigo(
        "prepararSalida('Marasi')",
        "esperar(prepararSalida('Steris')).igualA(['Wax', 'Wayne', 'Steris'])",
      ),
    },
    {
      nombre: "cada salida es una lista distinta",
      codigo: codigo(
        "const una = prepararSalida('Marasi')",
        "const otra = prepararSalida('Marasi')",
        "una.push('MeLaan')",
        "esperar(otra).tieneLongitud(3)",
      ),
    },
  ],
  pistas: [
    pista("`const equipo = PLANTILLA` no crea ninguna lista nueva. Le pone un segundo nombre a la que ya había.", 0),
    pista("Hace falta una lista nueva con el mismo contenido, y a esa sí se le puede hacer `push` tranquilamente.", 1),
    pista("La línea que hay que cambiar es la primera de la función, y el cambio cabe en tres puntos y un par de corchetes. Está en el apunte, en «Copiar de verdad». El `push` de después se queda exactamente como está.", 2),
  ],
  recompensa: { croquetas: 9 },
}
