import { codigo, pista } from '../comun.js'

export default {
  id: "taller-05-cierres",
  mundo: "taller",
  entorno: "worker",
  tipo: "codigo",
  titulo: "Funciones que se acuerdan",
  enunciado: codigo(
    "Una función puede **recordar** cosas entre llamada y llamada sin guardarlas en",
    "ningún sitio público. Eso es un cierre, y está debajo de media biblioteca que vas",
    "a usar en tu vida.",
    "",
    "Escribe `abrirCuenta(inicial)`, que devuelve un objeto con tres funciones:",
    "",
    "- `ingresar(cantidad)` — suma y devuelve el saldo nuevo.",
    "- `gastar(cantidad)` — resta si llega, y devuelve el saldo. Si no llega, no toca",
    "  nada y devuelve el saldo tal cual.",
    "- `saldo()` — devuelve el saldo actual.",
    "",
    "El saldo **no puede quedar accesible desde fuera**: solo se toca por esas tres.",
  ),
  apunte: codigo(
    "Una función declarada dentro de otra ve las variables de la de fuera. Y sigue",
    "viéndolas **después** de que la de fuera haya terminado:",
    "",
    "```js",
    "function contador() {",
    "  let veces = 0",
    "  return () => {",
    "    veces += 1",
    "    return veces",
    "  }",
    "}",
    "",
    "const contar = contador()",
    "contar()   // 1",
    "contar()   // 2",
    "```",
    "",
    "`contador()` ya terminó, y sin embargo `veces` sigue viva. No es magia: mientras",
    "alguien pueda usar esa variable, no se tira. A eso se le llama un **cierre**.",
    "",
    "## Para qué sirve de verdad",
    "",
    "Para tener datos **privados**. Compara:",
    "",
    "```js",
    "const cuenta = { saldo: 100 }",
    "cuenta.saldo = 999999          // nadie se lo impide",
    "```",
    "",
    "```js",
    "function abrirCuenta(inicial) {",
    "  let saldo = inicial",
    "  return {",
    "    ingresar(cantidad) { saldo += cantidad; return saldo },",
    "    saldo() { return saldo },",
    "  }",
    "}",
    "",
    "const c = abrirCuenta(100)",
    "c.saldo = 999999               // crea una propiedad nueva y no sirve de nada",
    "c.saldo()                      // 100. El de verdad no se toca.",
    "```",
    "",
    "La variable `saldo` no existe fuera. No hay forma de llegar a ella que no pase por",
    "las funciones que tú has escrito, y esas pueden comprobar lo que quieran antes de",
    "dejar hacer nada.",
    "",
    "## Cada llamada, su recuerdo",
    "",
    "```js",
    "const una = abrirCuenta(100)",
    "const otra = abrirCuenta(500)",
    "```",
    "",
    "Dos cuentas, dos `saldo` distintos que no se enteran el uno del otro. Cada vez que",
    "llamas a la función de fuera nace un juego nuevo de variables.",
    "",
    "Esto que parece un truco es exactamente lo que hace un composable de Vue, y lo que",
    "hacen los hooks de React. Cuando llegues allí, ya lo habrás entendido aquí.",
  ),
  inicial: codigo(
    "function abrirCuenta(inicial) {",
    "  // una variable aquí, y un objeto con tres funciones que la usan",
    "}",
    "",
    "const cuenta = abrirCuenta(100)",
    "cuenta.ingresar(50)",
    "console.log(cuenta.saldo())",
  ),
  solucion: codigo(
    "function abrirCuenta(inicial) {",
    "  let saldo = inicial",
    "",
    "  return {",
    "    ingresar(cantidad) {",
    "      saldo += cantidad",
    "      return saldo",
    "    },",
    "    gastar(cantidad) {",
    "      if (cantidad <= saldo) saldo -= cantidad",
    "      return saldo",
    "    },",
    "    saldo() {",
    "      return saldo",
    "    },",
    "  }",
    "}",
    "",
    "const cuenta = abrirCuenta(100)",
    "cuenta.ingresar(50)",
    "console.log(cuenta.saldo())",
  ),
  tests: [
    {
      nombre: "empieza con lo que le pongas",
      codigo: "esperar(abrirCuenta(100).saldo()).igualA(100)",
    },
    {
      nombre: "ingresar suma y devuelve el saldo nuevo",
      codigo: codigo(
        "const c = abrirCuenta(100)",
        "esperar(c.ingresar(50)).igualA(150)",
        "esperar(c.saldo()).igualA(150)",
      ),
    },
    {
      nombre: "se acuerda entre llamadas",
      codigo: codigo(
        "const c = abrirCuenta(0)",
        "c.ingresar(10)",
        "c.ingresar(10)",
        "c.ingresar(10)",
        "esperar(c.saldo()).igualA(30)",
      ),
    },
    {
      nombre: "gastar resta cuando llega",
      codigo: codigo(
        "const c = abrirCuenta(100)",
        "esperar(c.gastar(30)).igualA(70)",
      ),
    },
    {
      nombre: "y no deja la cuenta en números rojos",
      codigo: codigo(
        "const c = abrirCuenta(100)",
        "esperar(c.gastar(500)).igualA(100)",
        "esperar(c.saldo()).igualA(100)",
      ),
    },
    {
      nombre: "dos cuentas no comparten el saldo",
      codigo: codigo(
        "const una = abrirCuenta(100)",
        "const otra = abrirCuenta(500)",
        "una.ingresar(50)",
        "esperar(otra.saldo()).igualA(500)",
      ),
    },
    {
      nombre: "el saldo no se puede tocar desde fuera",
      codigo: codigo(
        "const c = abrirCuenta(100)",
        "c.saldo = 999999",
        "c.interno = 999999",
        "esperar(abrirCuenta(100).saldo()).igualA(100)",
      ),
    },
  ],
  pistas: [
    pista("La variable del saldo va en `abrirCuenta`, **antes** del `return`. Las tres funciones de dentro la ven.", 0),
    pista("Tiene que ser `let`: `const` no dejaría sumarle ni restarle.", 1),
    pista("`gastar` comprueba `if (cantidad <= saldo) saldo -= cantidad` y devuelve `saldo` en los dos casos, dentro o fuera del `if`.", 2),
  ],
  recompensa: { croquetas: 11 },
}
