import { codigo, pista } from '../comun.js'

export default {
  id: "fundacion-05-heredar",
  mundo: "fundacion",
  entorno: "php",
  tipo: "codigo",
  titulo: "Lo que ya estaba escrito",
  enunciado: codigo(
    "Heredar es decir «esto es como aquello, pero además». La clase hija tiene todo lo de la",
    "madre sin copiarlo, y puede añadir o cambiar lo que necesite.",
    "",
    "```php",
    "class Bruma extends Fenomeno { ... }",
    "```",
    "",
    "Dentro de la hija, `parent::algo()` llama a la versión de la madre. Sirve para",
    "**añadir** a lo que ya hacía en vez de repetirlo.",
    "",
    "Te damos `Aviso`. Escribe dos clases que hereden de ella:",
    "",
    "- `AvisoUrgente` — su `texto()` devuelve lo mismo que el de `Aviso` pero en mayúsculas y",
    "  con `'!'` al final.",
    "- `AvisoSilencioso` — su `texto()` devuelve el texto tal cual, y además su `prioridad()`",
    "  devuelve `0` en vez de `1`.",
  ),
  inicial: codigo(
    "<?php",
    "",
    "class Aviso",
    "{",
    "    public function __construct(protected string $mensaje) {}",
    "",
    "    public function texto(): string",
    "    {",
    "        return $this->mensaje;",
    "    }",
    "",
    "    public function prioridad(): int",
    "    {",
    "        return 1;",
    "    }",
    "}",
    "",
    "// Las dos hijas. No repitas el constructor: ya lo tienen.",
  ),
  solucion: codigo(
    "<?php",
    "",
    "class Aviso",
    "{",
    "    public function __construct(protected string $mensaje) {}",
    "",
    "    public function texto(): string",
    "    {",
    "        return $this->mensaje;",
    "    }",
    "",
    "    public function prioridad(): int",
    "    {",
    "        return 1;",
    "    }",
    "}",
    "",
    "class AvisoUrgente extends Aviso",
    "{",
    "    public function texto(): string",
    "    {",
    "        return strtoupper(parent::texto()) . '!';",
    "    }",
    "}",
    "",
    "class AvisoSilencioso extends Aviso",
    "{",
    "    public function prioridad(): int",
    "    {",
    "        return 0;",
    "    }",
    "}",
  ),
  requisitos: [
    { tipo: "usaPalabra", valor: "extends", texto: "Hereda con `extends`" },
    { tipo: "usaPalabra", valor: "parent", texto: "Reutiliza lo de la madre con `parent::`" },
  ],
  tests: [
    {
      nombre: "el aviso normal sigue igual",
      codigo: codigo(
        "$uno = new Aviso('bruma al norte');",
        "esperar($uno->texto(), 'el texto')->igualA('bruma al norte');",
        "esperar($uno->prioridad(), 'la prioridad')->igualA(1);",
      ),
    },
    {
      nombre: "el urgente grita",
      codigo: "esperar((new AvisoUrgente('bruma'))->texto(), 'el texto')->igualA('BRUMA!');",
    },
    {
      nombre: "y hereda la prioridad sin escribirla",
      codigo: "esperar((new AvisoUrgente('bruma'))->prioridad(), 'la prioridad')->igualA(1);",
    },
    {
      nombre: "el silencioso no toca el texto",
      codigo: "esperar((new AvisoSilencioso('bruma'))->texto(), 'el texto')->igualA('bruma');",
    },
    {
      nombre: "pero baja su prioridad a cero",
      codigo: "esperar((new AvisoSilencioso('bruma'))->prioridad(), 'la prioridad')->igualA(0);",
    },
    {
      nombre: "las dos son avisos, y eso es lo que hace útil heredar",
      codigo: codigo(
        "esperar(new AvisoUrgente('x') instanceof Aviso, 'urgente es un aviso')->esVerdadero();",
        "esperar(new AvisoSilencioso('x') instanceof Aviso, 'silencioso es un aviso')->esVerdadero();",
      ),
    },
    {
      nombre: "y una lista de avisos mezclados se recorre igual",
      codigo: codigo(
        "$todos = [new Aviso('a'), new AvisoUrgente('b'), new AvisoSilencioso('c')];",
        "esperar(array_map(fn($u) => $u->texto(), $todos), 'los textos')->igualA(['a', 'B!', 'c']);",
      ),
    },
  ],
  variantes: [
    {
      titulo: "Lo que ya estaba escrito · otra tanda",
      tests: [
        { nombre: "un urgente con espacios", codigo: "esperar((new AvisoUrgente('cae ceniza'))->texto(), 'el texto')->igualA('CAE CENIZA!');" },
        { nombre: "un urgente vacío sigue llevando su signo", codigo: "esperar((new AvisoUrgente(''))->texto(), 'el texto')->igualA('!');" },
        { nombre: "el silencioso con texto largo", codigo: "esperar((new AvisoSilencioso('todo en orden'))->texto(), 'el texto')->igualA('todo en orden');" },
        {
          nombre: "las prioridades de los tres",
          codigo: codigo(
            "$todos = [new Aviso('a'), new AvisoUrgente('b'), new AvisoSilencioso('c')];",
            "esperar(array_map(fn($u) => $u->prioridad(), $todos), 'las prioridades')->igualA([1, 1, 0]);",
          ),
        },
      ],
    },
  ],
  pistas: [
    pista("`class Hija extends Madre` y ya está: la hija tiene el constructor y los métodos de la madre sin escribir nada.", 0),
    pista("Para cambiar un método, escríbelo otra vez en la hija con el mismo nombre. Lo que no escribas se queda como estaba.", 1),
    pista("Dentro del método de la hija, `parent::texto()` da lo que devolvería la madre. Eso se puede envolver: `strtoupper(parent::texto())`.", 2),
  ],
  recompensa: { croquetas: 10 },
}
