import { codigo, pista } from '../comun.js'

export default {
  id: "dia1-02-tipos",
  mundo: "primer-dia",
  entorno: "worker",
  tipo: "emparejar",
  titulo: "Cada cosa de su clase",
  enunciado: codigo(
    "No todo lo que se guarda es igual. Un nombre no es un número, y una lista de",
    "gatos no es un gato.",
    "",
    "Empareja cada valor con lo que es. Pulsa uno de la izquierda y su pareja de la derecha.",
  ),
  apunte: codigo(
    "En JavaScript hay unos pocos tipos de valor, y con estos cinco te apañas casi",
    "siempre:",
    "",
    "```js",
    "'Wayne'              // texto: entre comillas",
    "42                   // número: sin comillas",
    "true                 // booleano: solo puede ser true o false",
    "['Wax', 'Marasi']    // lista (array): varios valores en orden, entre corchetes",
    "{ nombre: 'Wayne' }  // objeto: valores con nombre",
    "```",
    "",
    "Y uno más que confunde a todo el mundo al principio:",
    "",
    "```js",
    "null   // «aquí no hay nada, y es a propósito»",
    "```",
    "",
    "La diferencia entre `42` y `'42'` no es un capricho: con el primero puedes",
    "sumar; con el segundo, si lo intentas, JavaScript pega textos y te salen cosas",
    "raras. Ya te tocará ver una.",
  ),
  parejas: [
    { izquierda: "'bombín'", derecha: "Un texto" },
    { izquierda: "42", derecha: "Un número" },
    { izquierda: "true", derecha: "Un booleano: verdadero o falso" },
    { izquierda: "['Acero', 'Bronce']", derecha: "Una lista de valores en orden" },
    { izquierda: "{ nombre: 'Wayne' }", derecha: "Un objeto: valores con nombre" },
    { izquierda: "null", derecha: "Aquí no hay nada, y es a propósito" },
  ],
  pistas: [
    pista("Mírale los signos de fuera a cada uno: las comillas, los corchetes, las llaves. Cada envoltorio delata lo que hay dentro.", 0),
    pista("Los corchetes `[ ]` son de listas. Las llaves `{ }`, de objetos. Las comillas, de texto.", 1),
    pista("Comillas → texto. Sin comillas y con cifras → número. `true` → booleano. `[ ]` → lista. `{ }` → objeto. `null` → nada, aposta.", 2),
  ],
  recompensa: { croquetas: 5 },
}
