import { codigo, pista } from '../comun.js'

export default {
  id: "dia1-02-tipos",
  mundo: "primer-dia",
  entorno: "worker",
  tipo: "emparejar",
  titulo: "Cada cosa de su clase",
  enunciado: codigo(
    "No todo lo que se guarda es igual. Un nombre no es un número, y una lista de",
    "gatos no es un gato.",
    "",
    "Empareja cada valor con lo que es. Pulsa uno de la izquierda y su pareja de la derecha.",
  ),
  apunte: codigo(
    "En una ficha de busca y captura no todo es de la misma clase: el nombre es texto,",
    "la recompensa es una cifra, y «visto con vida» es un sí o un no. En JavaScript",
    "pasa igual, y con estos cinco te apañas casi siempre:",
    "",
    "```js",
    "'Wayne'              // texto: entre comillas",
    "500                  // número: sin comillas",
    "true                 // booleano: solo true o false",
    "['Wax', 'Marasi']    // lista: varios valores en orden",
    "{ nombre: 'Wayne' }  // objeto: valores con nombre",
    "```",
    "",
    "Y uno más, que confunde a todo el mundo al principio:",
    "",
    "```js",
    "null   // «aquí no hay nada, y consta que no lo hay»",
    "```",
    "",
    "`null` no es lo mismo que un cero ni que un texto vacío. Es la casilla de la ficha",
    "que se dejó en blanco **a propósito**.",
    "",
    "La diferencia entre `500` y `'500'` no es un capricho de la máquina: con el",
    "primero puedes sumar recompensas; con el segundo, si lo intentas, JavaScript pega",
    "los textos y te salen cifras que no existen. Ya te tocará ver una.",
  ),
  parejas: [
    { izquierda: "'bombín'", derecha: "Un texto" },
    { izquierda: "42", derecha: "Un número" },
    { izquierda: "true", derecha: "Un booleano: verdadero o falso" },
    { izquierda: "['Acero', 'Bronce']", derecha: "Una lista de valores en orden" },
    { izquierda: "{ nombre: 'Wayne' }", derecha: "Un objeto: valores con nombre" },
    { izquierda: "null", derecha: "Aquí no hay nada, y es a propósito" },
  ],
  pistas: [
    pista("Mírale los signos de fuera a cada uno: las comillas, los corchetes, las llaves. Cada envoltorio delata lo que hay dentro.", 0),
    pista("Los corchetes `[ ]` son de listas. Las llaves `{ }`, de objetos. Las comillas, de texto.", 1),
    pista("Comillas → texto. Sin comillas y con cifras → número. `true` → booleano. `[ ]` → lista. `{ }` → objeto. `null` → nada, aposta.", 2),
  ],
  recompensa: { croquetas: 5 },
}
