import { codigo, pista } from '../comun.js'

export default {
  id: "elendel-01-modulos",
  mundo: "elendel",
  entorno: "worker",
  tipo: "etiquetar",
  titulo: "Un archivo ya no basta",
  enunciado: codigo(
    "Todo lo que has escrito hasta ahora cabía en un archivo. Ningún programa de verdad",
    "cabe en un archivo, y la forma de repartirlo son los **módulos**.",
    "",
    "Este juego está hecho de módulos: cada reto, cada apunte y cada pieza del motor es",
    "uno. Aquí hay dos, el que exporta y el que importa. Ponle nombre a cada parte.",
  ),
  fragmentos: [
    { texto: "// ── tarifas.js ────────────────────────\n\n" },
    { texto: "export const TARIFA_DIARIA = 25", etiqueta: "exportación con nombre" },
    { texto: "\n\nexport function cobrar(dias) {\n  return TARIFA_DIARIA * dias\n}\n\n" },
    { texto: "export default cobrar", etiqueta: "exportación por defecto" },
    { texto: "\n\n// ── informe.js ────────────────────────\n\n" },
    { texto: "import cobrar", etiqueta: "importación de lo que va por defecto" },
    { texto: ", " },
    { texto: "{ TARIFA_DIARIA }", etiqueta: "importación con nombre" },
    { texto: " " },
    { texto: "from './tarifas.js'", etiqueta: "de qué archivo viene" },
    { texto: "\n\nconsole.log(cobrar(3))" },
  ],
  etiquetas: [
    "exportación con nombre",
    "exportación por defecto",
    "importación de lo que va por defecto",
    "importación con nombre",
    "de qué archivo viene",
    "declaración de variable",
    "llamada a una función",
    "comentario",
  ],
  porque: codigo(
    "La diferencia que hay que llevarse: **lo que va con nombre se importa entre llaves y",
    "con su nombre exacto; lo que va por defecto se importa sin llaves y se puede llamar",
    "como quieras.**",
    "",
    "```js",
    "import cobrar from './tarifas.js'        // era `export default`",
    "import loQueSea from './tarifas.js'      // el mismo, con otro nombre. Vale igual",
    "import { TARIFA_DIARIA } from './tarifas.js'   // este tiene que llamarse así",
    "```",
    "",
    "Y una regla que ahorra discusiones: **lo que no se exporta, no existe fuera**. Un",
    "módulo no comparte nada por accidente, solo lo que decide. Eso es justo lo contrario",
    "de lo que pasaba cuando todo iba en un archivo, donde cualquier variable podía chocar",
    "con cualquier otra.",
  ),
  pistas: [
    pista("Hay dos formas de sacar cosas de un archivo y dos de meterlas. Fíjate en cuál lleva la palabra `default`.", 0),
    pista("En la línea de `import`, lo que va entre llaves y lo que va suelto no vienen de la misma clase de exportación.", 1),
    pista("La ruta del final no es una etiqueta de adorno: es lo único que dice de dónde salen las dos cosas que se acaban de importar.", 2),
  ],
  recompensa: { croquetas: 11 },
}
