import { codigo, pista } from '../comun.js'

export default {
  id: "vue2-03-eventos",
  mundo: "vue2",
  entorno: "vue2",
  tipo: "codigo",
  titulo: "Apuntar el botín",
  enunciado: codigo(
    "Ahora la casa tiene que responder. Un campo donde escribir, un botón que guarda y una",
    "lista que crece.",
    "",
    "Declara `componente` con:",
    "",
    "- `data`: `nuevo` (texto vacío) y `botin` (lista vacía)",
    "- un método `guardar()` que meta lo escrito en `botin` y **deje el campo vacío**",
    "- si lo escrito está en blanco o son solo espacios, que no guarde nada",
    "- plantilla con `<input class=\"campo\">` atado a `nuevo`, un `<button class=\"guardar\">`,",
    "  un `<li>` por cada cosa del botín y un `<p class=\"cuenta\">` con cuántas van",
    "",
    "Para atar el campo al dato se usa `v-model`, y para el botón, `@click`.",
  ),
  inicial: codigo(
    "const componente = {",
    "  data() {",
    "    return { nuevo: '', botin: [] }",
    "  },",
    "  methods: {",
    "    guardar() {",
    "      // Guarda lo escrito, si es que hay algo escrito.",
    "    },",
    "  },",
    "  template: `",
    "    <div>",
    "    </div>",
    "  `,",
    "}",
  ),
  solucion: codigo(
    "const componente = {",
    "  data() {",
    "    return { nuevo: '', botin: [] }",
    "  },",
    "  methods: {",
    "    guardar() {",
    "      const limpio = this.nuevo.trim()",
    "      if (limpio === '') return",
    "      this.botin.push(limpio)",
    "      this.nuevo = ''",
    "    },",
    "  },",
    "  template: `",
    "    <div>",
    "      <input class=\"campo\" v-model=\"nuevo\" />",
    "      <button class=\"guardar\" @click=\"guardar\">Guardar</button>",
    "      <ul>",
    "        <li v-for=\"(cosa, i) in botin\" :key=\"i\">{{ cosa }}</li>",
    "      </ul>",
    "      <p class=\"cuenta\">{{ botin.length }}</p>",
    "    </div>",
    "  `,",
    "}",
  ),
  requisitos: [
    { tipo: "declaraVariable", valor: "componente" },
    { tipo: "usaPropiedad", valor: "methods" },
  ],
  tests: [
    {
      nombre: "empieza con el botín vacío",
      codigo: codigo(
        "const caja = montar(componente)",
        "esperar(caja.contar('li')).igualA(0)",
        "esperar(caja.texto('.cuenta')).igualA('0')",
      ),
    },
    {
      nombre: "guarda lo que se escribe",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', 'Mentemetal')",
        "await caja.click('.guardar')",
        "esperar(caja.textos('li')).igualA(['Mentemetal'])",
        "esperar(caja.texto('.cuenta')).igualA('1')",
      ),
    },
    {
      nombre: "deja el campo listo para lo siguiente",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', 'Vindicación')",
        "await caja.click('.guardar')",
        "esperar(caja.valor('.campo'), 'lo que queda en el campo').igualA('')",
        "esperar(caja.vm.nuevo, 'el dato nuevo').igualA('')",
      ),
    },
    {
      nombre: "guarda varias cosas seguidas",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', 'Sombrero')",
        "await caja.click('.guardar')",
        "await caja.escribir('.campo', 'Chicle')",
        "await caja.click('.guardar')",
        "esperar(caja.textos('li')).igualA(['Sombrero', 'Chicle'])",
      ),
    },
    {
      nombre: "no guarda espacios en blanco",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', '   ')",
        "await caja.click('.guardar')",
        "esperar(caja.contar('li'), 'filas tras intentar guardar nada').igualA(0)",
      ),
    },
  ],
  // Lo que se practica es el orden del método: limpiar, salir si no queda nada,
  // guardar y vaciar el campo. Estas tandas atacan cada paso por separado.
  variantes: [
    {
      titulo: "Apuntar el botín · otra tanda",
      tests: [
        {
          nombre: "los espacios de los lados se recortan antes de guardar",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', '   Chicle   ')",
            "await caja.click('.guardar')",
            "esperar(caja.textos('li')).igualA(['Chicle'])",
          ),
        },
        {
          nombre: "pulsar guardar sin haber escrito nada no apunta nada",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.click('.guardar')",
            "esperar(caja.contar('li')).igualA(0)",
            "esperar(caja.texto('.cuenta')).igualA('0')",
          ),
        },
        {
          nombre: "tres cosas seguidas y la cuenta va con ellas",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', 'Vindicación')",
            "await caja.click('.guardar')",
            "await caja.escribir('.campo', 'Sombrero')",
            "await caja.click('.guardar')",
            "await caja.escribir('.campo', 'Chicle')",
            "await caja.click('.guardar')",
            "esperar(caja.texto('.cuenta')).igualA('3')",
            "esperar(caja.textos('li')).igualA(['Vindicación', 'Sombrero', 'Chicle'])",
          ),
        },
        {
          nombre: "guardar lo mismo dos veces lo apunta dos veces: nadie dijo que fuera un conjunto",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', 'Chicle')",
            "await caja.click('.guardar')",
            "await caja.escribir('.campo', 'Chicle')",
            "await caja.click('.guardar')",
            "esperar(caja.textos('li')).igualA(['Chicle', 'Chicle'])",
          ),
        },
        {
          nombre: "y el campo y el botón están donde los buscan los tests",
          codigo: codigo(
            "const caja = montar(componente)",
            "esperar(caja.existe('.campo'), 'el campo').esVerdadero()",
            "esperar(caja.existe('.guardar'), 'el botón').esVerdadero()",
          ),
        },
      ],
    },
    {
      titulo: "Apuntar el botín · y otra",
      tests: [
        {
          nombre: "un tabulador entre espacios tampoco es un objeto que guardar",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', '  \\t  ')",
            "await caja.click('.guardar')",
            "esperar(caja.contar('li')).igualA(0)",
          ),
        },
        {
          nombre: "insistir en el botón después de guardar no duplica lo guardado",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', 'Mentemetal')",
            "await caja.click('.guardar')",
            "await caja.click('.guardar')",
            "esperar(caja.textos('li')).igualA(['Mentemetal'])",
          ),
        },
        {
          nombre: "el campo y el dato van a la par: eso es lo que hace v-model",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', 'Vindicación')",
            "esperar(caja.vm.nuevo, 'el dato nuevo').igualA('Vindicación')",
          ),
        },
        {
          nombre: "la cuenta sube de uno en uno, y se pinta",
          codigo: codigo(
            "const caja = montar(componente)",
            "await caja.escribir('.campo', 'uno')",
            "await caja.click('.guardar')",
            "esperar(caja.texto('.cuenta')).igualA('1')",
            "await caja.escribir('.campo', 'dos')",
            "await caja.click('.guardar')",
            "esperar(caja.texto('.cuenta')).igualA('2')",
          ),
        },
        {
          nombre: "y el botín es una lista, no un texto donde se van pegando cosas",
          codigo: codigo(
            "const caja = montar(componente)",
            "esperar(Array.isArray(caja.vm.botin), 'que el botín sea una lista').esVerdadero()",
          ),
        },
      ],
    },
  ],
  pistas: [
    pista("`v-model=\"nuevo\"` ata el campo al dato en los dos sentidos. `@click=\"guardar\"` llama al método al pulsar.", 0),
    pista("Dentro del método, `this.nuevo` es lo escrito y `this.botin` la lista. Para no guardar espacios, mira `this.nuevo.trim()`.", 1),
    pista("El método hace tres cosas y en este orden: limpia lo escrito, se va sin hacer nada si quedó vacío, y si no, lo mete en la lista. Y luego una cuarta que es la que todo el mundo olvida: dejar el campo vacío para el siguiente.", 2),
  ],
  recompensa: { croquetas: 12 },
}
