import { codigo, pista } from '../comun.js'

export default {
  id: "vue2-03-eventos",
  mundo: "vue2",
  entorno: "vue2",
  tipo: "codigo",
  titulo: "Apuntar el botín",
  enunciado: codigo(
    "Ahora la casa tiene que responder. Un campo donde escribir, un botón que guarda y una",
    "lista que crece.",
    "",
    "Declara `componente` con:",
    "",
    "- `data`: `nuevo` (texto vacío) y `botin` (lista vacía)",
    "- un método `guardar()` que meta lo escrito en `botin` y **deje el campo vacío**",
    "- si lo escrito está en blanco o son solo espacios, que no guarde nada",
    "- plantilla con `<input class=\"campo\">` atado a `nuevo`, un `<button class=\"guardar\">`,",
    "  un `<li>` por cada cosa del botín y un `<p class=\"cuenta\">` con cuántas van",
    "",
    "Para atar el campo al dato se usa `v-model`, y para el botón, `@click`.",
  ),
  apunte: codigo(
    "Para que la casa responda hacen falta dos cosas.",
    "",
    "**Escuchar** con `@`, que es la forma corta de `v-on`:",
    "",
    "```html",
    "<button @click=\"guardar\">Guardar</button>",
    "```",
    "",
    "**Atar un campo a un dato** con `v-model`, que va en los dos sentidos: escribes en",
    "el campo y cambia el dato; cambia el dato y se actualiza el campo.",
    "",
    "```html",
    "<input v-model=\"nuevo\" />",
    "```",
    "",
    "Los métodos van en su cajón, y ahí dentro los datos se leen y se escriben por",
    "`this`:",
    "",
    "```js",
    "methods: {",
    "  guardar() {",
    "    this.botin.push(this.nuevo)",
    "    this.nuevo = ''       // vaciar el dato vacía el campo solo",
    "  },",
    "}",
    "```",
    "",
    "Fíjate en la última línea: **no se toca el campo, se toca el dato**. El campo es",
    "un reflejo. Cuando alguien intenta manipular la vista por su cuenta en vez de",
    "cambiar lo que la vista refleja es cuando empiezan los problemas raros.",
    "",
    "Y `.trim()` quita los espacios de los extremos: sirve para no dar por bueno un",
    "apunte en el que solo hay aire.",
  ),
  inicial: codigo(
    "const componente = {",
    "  data() {",
    "    return { nuevo: '', botin: [] }",
    "  },",
    "  methods: {",
    "    guardar() {",
    "      // Guarda lo escrito, si es que hay algo escrito.",
    "    },",
    "  },",
    "  template: `",
    "    <div>",
    "    </div>",
    "  `,",
    "}",
  ),
  solucion: codigo(
    "const componente = {",
    "  data() {",
    "    return { nuevo: '', botin: [] }",
    "  },",
    "  methods: {",
    "    guardar() {",
    "      const limpio = this.nuevo.trim()",
    "      if (limpio === '') return",
    "      this.botin.push(limpio)",
    "      this.nuevo = ''",
    "    },",
    "  },",
    "  template: `",
    "    <div>",
    "      <input class=\"campo\" v-model=\"nuevo\" />",
    "      <button class=\"guardar\" @click=\"guardar\">Guardar</button>",
    "      <ul>",
    "        <li v-for=\"(cosa, i) in botin\" :key=\"i\">{{ cosa }}</li>",
    "      </ul>",
    "      <p class=\"cuenta\">{{ botin.length }}</p>",
    "    </div>",
    "  `,",
    "}",
  ),
  requisitos: [
    { tipo: "declaraVariable", valor: "componente" },
    { tipo: "usaPropiedad", valor: "methods" },
  ],
  tests: [
    {
      nombre: "empieza con el botín vacío",
      codigo: codigo(
        "const caja = montar(componente)",
        "esperar(caja.contar('li')).igualA(0)",
        "esperar(caja.texto('.cuenta')).igualA('0')",
      ),
    },
    {
      nombre: "guarda lo que se escribe",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', 'Mentemetal')",
        "await caja.click('.guardar')",
        "esperar(caja.textos('li')).igualA(['Mentemetal'])",
        "esperar(caja.texto('.cuenta')).igualA('1')",
      ),
    },
    {
      nombre: "deja el campo listo para lo siguiente",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', 'Vindicación')",
        "await caja.click('.guardar')",
        "esperar(caja.valor('.campo'), 'lo que queda en el campo').igualA('')",
        "esperar(caja.vm.nuevo, 'el dato nuevo').igualA('')",
      ),
    },
    {
      nombre: "guarda varias cosas seguidas",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', 'Sombrero')",
        "await caja.click('.guardar')",
        "await caja.escribir('.campo', 'Chicle')",
        "await caja.click('.guardar')",
        "esperar(caja.textos('li')).igualA(['Sombrero', 'Chicle'])",
      ),
    },
    {
      nombre: "no guarda espacios en blanco",
      codigo: codigo(
        "const caja = montar(componente)",
        "await caja.escribir('.campo', '   ')",
        "await caja.click('.guardar')",
        "esperar(caja.contar('li'), 'filas tras intentar guardar nada').igualA(0)",
      ),
    },
  ],
  pistas: [
    pista("`v-model=\"nuevo\"` ata el campo al dato en los dos sentidos. `@click=\"guardar\"` llama al método al pulsar.", 0),
    pista("Dentro del método, `this.nuevo` es lo escrito y `this.botin` la lista. Para no guardar espacios, mira `this.nuevo.trim()`.", 1),
    pista("El método hace tres cosas y en este orden: limpia lo escrito, se va sin hacer nada si quedó vacío, y si no, lo mete en la lista. Y luego una cuarta que es la que todo el mundo olvida: dejar el campo vacío para el siguiente.", 2),
  ],
  recompensa: { croquetas: 12 },
}
