import { codigo, pista } from '../comun.js'

export default {
  id: "tripulacion-01-decidir",
  mundo: "tripulacion",
  entorno: "php",
  tipo: "codigo",
  titulo: "Que decida el programa",
  enunciado: codigo(
    "Hasta ahora tu código hacía siempre lo mismo. Un `if` es lo que le permite mirar antes",
    "de actuar.",
    "",
    "Escribe dos funciones:",
    "",
    "- `clasificar(int $cantidad)` — devuelve `'mucho'` de 100 arriba, `'suficiente'` de 20 a 99,",
    "  `'poco'` de 1 a 19 y `'nada'` con 0 o menos.",
    "- `esSeguro(bool $bruma, int $vigilantes)` — devuelve `true` solo si hay bruma **y** hay",
    "  menos de tres vigilantes.",
    "",
    "Las dos con `if`. Nada de `match`, que llega más adelante.",
  ),
  inicial: codigo(
    "<?php",
    "",
    "function clasificar(int $cantidad): string",
    "{",
    "    // Cuatro tramos. Piensa en qué orden hay que preguntarlos.",
    "}",
    "",
    "function esSeguro(bool $bruma, int $vigilantes): bool",
    "{",
    "    // Dos condiciones que se tienen que cumplir las dos.",
    "}",
  ),
  solucion: codigo(
    "<?php",
    "",
    "function clasificar(int $cantidad): string",
    "{",
    "    if ($cantidad >= 100) {",
    "        return 'mucho';",
    "    }",
    "    if ($cantidad >= 20) {",
    "        return 'suficiente';",
    "    }",
    "    if ($cantidad > 0) {",
    "        return 'poco';",
    "    }",
    "    return 'nada';",
    "}",
    "",
    "function esSeguro(bool $bruma, int $vigilantes): bool",
    "{",
    "    if ($bruma && $vigilantes < 3) {",
    "        return true;",
    "    }",
    "    return false;",
    "}",
  ),
  requisitos: [
    { tipo: "usaPalabra", valor: "if", texto: "Decide con `if`" },
    { tipo: "prohibePalabra", valor: "match", texto: "Sin `match`: aquí se practica el `if`" },
  ],
  tests: [
    { nombre: "cien ya es mucho", codigo: "esperar(clasificar(100))->igualA('mucho');" },
    { nombre: "quinientos también", codigo: "esperar(clasificar(500))->igualA('mucho');" },
    { nombre: "noventa y nueve es suficiente", codigo: "esperar(clasificar(99))->igualA('suficiente');" },
    { nombre: "veinte es el borde de suficiente", codigo: "esperar(clasificar(20))->igualA('suficiente');" },
    { nombre: "diecinueve ya es poco", codigo: "esperar(clasificar(19))->igualA('poco');" },
    { nombre: "uno es poco", codigo: "esperar(clasificar(1))->igualA('poco');" },
    { nombre: "cero es nada", codigo: "esperar(clasificar(0))->igualA('nada');" },
    { nombre: "y en negativo, tampoco hay nada", codigo: "esperar(clasificar(-5))->igualA('nada');" },
    { nombre: "con bruma y dos vigilantes, seguro", codigo: "esperar(esSeguro(true, 2))->esVerdadero();" },
    { nombre: "con bruma y tres, ya no", codigo: "esperar(esSeguro(true, 3))->esFalso();" },
    { nombre: "sin bruma no hay nada seguro", codigo: "esperar(esSeguro(false, 0))->esFalso();" },
  ],
  variantes: [
    {
      titulo: "Que decida el programa · otra tanda",
      tests: [
        { nombre: "ciento uno", codigo: "esperar(clasificar(101))->igualA('mucho');" },
        { nombre: "veintiuno", codigo: "esperar(clasificar(21))->igualA('suficiente');" },
        { nombre: "dos", codigo: "esperar(clasificar(2))->igualA('poco');" },
        { nombre: "menos uno", codigo: "esperar(clasificar(-1))->igualA('nada');" },
        { nombre: "bruma y ninguno", codigo: "esperar(esSeguro(true, 0))->esVerdadero();" },
        { nombre: "bruma y diez", codigo: "esperar(esSeguro(true, 10))->esFalso();" },
        { nombre: "sin bruma, con dos", codigo: "esperar(esSeguro(false, 2))->esFalso();" },
      ],
    },
  ],
  pistas: [
    pista("`if ($algo) { ... }` ejecuta lo de dentro solo cuando la condición se cumple.", 0),
    pista("El orden de los tramos importa: si preguntas primero por «mayor que 0», el 500 también lo cumple y se queda ahí. Empieza por el tramo más alto.", 1),
    pista("Con un `return` dentro de cada `if` no hace falta `else`: al devolver, la función termina y lo de abajo ya no se mira. Y `&&` significa «las dos cosas».", 2),
  ],
  recompensa: { croquetas: 6 },
}
