import { codigo, pista } from '../comun.js'

export default {
  id: "vue3-04-watch",
  mundo: "vue3",
  entorno: "vue3",
  tipo: "codigo",
  titulo: "Dos formas de estar pendiente",
  enunciado: codigo(
    "`watch` y `watchEffect` se parecen y no son lo mismo, y la diferencia se ve en el primer",
    "segundo de vida del componente:",
    "",
    "- `watch(algo, (nuevo, viejo) => ...)` **espera**. No hace nada hasta que ese algo cambia, y",
    "  entonces te da el valor nuevo y el viejo.",
    "- `watchEffect(() => ...)` **se lanza enseguida**, una vez, y a partir de ahí se vuelve a",
    "  lanzar cuando cambia cualquier cosa que haya leído por dentro.",
    "",
    "Declara `componente` con un `setup()` que devuelva `balas` (un `ref` en 6), `registro` (un",
    "`ref` con una lista vacía) y `disparar()`. Y monta los dos vigilantes:",
    "",
    "- un `watch` sobre `balas` que apunte `watch: viejo -> nuevo`",
    "- un `watchEffect` que apunte `watchEffect: N`",
    "",
    "Regístralos en ese orden. Plantilla: `<p class=\"balas\">` y `<button class=\"disparar\">`.",
  ),
  apunte: codigo(
    "Dos centinelas que se parecen y no son lo mismo.",
    "",
    "**`watch`** espera. No hace nada hasta que cambia lo que vigila, y entonces te da",
    "el valor nuevo y el viejo:",
    "",
    "```js",
    "watch(balas, (nuevo, viejo) => {",
    "  console.log(`de ${viejo} a ${nuevo}`)",
    "})",
    "```",
    "",
    "**`watchEffect`** se lanza enseguida, una vez, y averigua solo de qué depende",
    "mirando lo que lee por dentro. A partir de ahí se vuelve a lanzar cuando cambie",
    "cualquiera de esas cosas:",
    "",
    "```js",
    "watchEffect(() => {",
    "  console.log(`ahora quedan ${balas.value}`)   // se ejecuta ya",
    "})",
    "```",
    "",
    "Cuál usar:",
    "",
    "- Necesitas el **valor anterior**, o vigilar algo muy concreto → `watch`.",
    "- Quieres mantener algo al día y el valor viejo te da igual → `watchEffect`.",
    "",
    "`watch` es el que apunta en el parte «tenía seis, ahora tiene cuatro».",
    "`watchEffect` es el que va diciendo en voz alta cuántas quedan, empezando ahora",
    "mismo.",
    "",
    "Y si lo único que quieres es **calcular** un valor a partir de otros, no uses",
    "ninguno de los dos: eso es `computed`.",
  ),
  inicial: codigo(
    "const { ref, watch, watchEffect } = Vue",
    "",
    "const componente = {",
    "  setup() {",
    "    const balas = ref(6)",
    "    const registro = ref([])",
    "",
    "    // Primero el watch, después el watchEffect.",
    "",
    "    const disparar = () => {",
    "      balas.value -= 1",
    "    }",
    "",
    "    return { balas, registro, disparar }",
    "  },",
    "  template: `",
    "    <div>",
    "      <p class=\"balas\">{{ balas }}</p>",
    "      <button class=\"disparar\" @click=\"disparar\">Disparar</button>",
    "    </div>",
    "  `,",
    "}",
  ),
  solucion: codigo(
    "const { ref, watch, watchEffect } = Vue",
    "",
    "const componente = {",
    "  setup() {",
    "    const balas = ref(6)",
    "    const registro = ref([])",
    "",
    "    watch(balas, (nuevo, viejo) => {",
    "      registro.value.push(`watch: ${viejo} -> ${nuevo}`)",
    "    })",
    "",
    "    watchEffect(() => {",
    "      registro.value.push(`watchEffect: ${balas.value}`)",
    "    })",
    "",
    "    const disparar = () => {",
    "      balas.value -= 1",
    "    }",
    "",
    "    return { balas, registro, disparar }",
    "  },",
    "  template: `",
    "    <div>",
    "      <p class=\"balas\">{{ balas }}</p>",
    "      <button class=\"disparar\" @click=\"disparar\">Disparar</button>",
    "    </div>",
    "  `,",
    "}",
  ),
  requisitos: [
    { tipo: "usaLlamada", valor: "watch" },
    { tipo: "usaLlamada", valor: "watchEffect" },
    { tipo: "declaraVariable", valor: "componente" },
  ],
  tests: [
    {
      nombre: "nada más montar, solo ha hablado watchEffect",
      codigo: codigo(
        "const puesto = montar(componente)",
        "esperar(puesto.vm.registro, 'el registro recién montado').igualA(['watchEffect: 6'])",
      ),
    },
    {
      nombre: "al cambiar, hablan los dos",
      codigo: codigo(
        "const puesto = montar(componente)",
        "await puesto.click('.disparar')",
        "esperar(puesto.vm.registro).contiene('watch: 6 -> 5')",
        "esperar(puesto.vm.registro).contiene('watchEffect: 5')",
      ),
    },
    {
      nombre: "el watch trae el valor viejo y el nuevo",
      codigo: codigo(
        "const puesto = montar(componente)",
        "await puesto.click('.disparar')",
        "await puesto.click('.disparar')",
        "esperar(puesto.vm.registro).contiene('watch: 5 -> 4')",
      ),
    },
    {
      nombre: "cada disparo deja dos apuntes",
      codigo: codigo(
        "const puesto = montar(componente)",
        "await puesto.click('.disparar')",
        "await puesto.click('.disparar')",
        "esperar(puesto.vm.registro.length, 'apuntes tras dos disparos').igualA(5)",
      ),
    },
  ],
  pistas: [
    pista("`watch` quiere dos cosas: qué vigilar y qué hacer cuando cambie. `watchEffect` solo quiere lo segundo, y averigua solo qué está vigilando.", 0),
    pista("Al montar, el registro tiene exactamente un apunte. Si te salen dos, has puesto el watch con `immediate: true` sin querer.", 1),
    pista("`watch(balas, (nuevo, viejo) => registro.value.push(`watch: ${viejo} -> ${nuevo}`))` y luego `watchEffect(() => registro.value.push(`watchEffect: ${balas.value}`))`.", 2),
  ],
  recompensa: { croquetas: 14 },
}
